- a00_(cholera)
- a01_(typhoid_and_paratyphoid_fevers)
- a02_(other_salmonella_infections)
- a03_(shigellosis)
- a04_(other_bacterial_intestinal_infections)
- a05_(other_bacterial_foodborne_intoxications)
- a06_(amoebiasis)
- a07_(other_protozoal_intestinal_diseases)
- a08_(viral_and_other_specified_intestinal_infections)
- a09_(diarrhoea_and_gastro-enteritis_of_presumed_infectious_origin)
- a15_(respiratory_tuberculosis,_bacteriologically_and_histologically_confirmed)
- a16_(respiratory_tuberculosis,_not_confirmed_bacteriologically_or_histologically)
- a17_(tuberculosis_of_nervous_system)
- a18_(tuberculosis_of_other_organs)
- a19_(miliary_tuberculosis)
- a20_(plague)
- a22_(anthrax)
- a23_(brucellosis)
- a24_(glanders_and_melioidosis)
- a25_(rat-bite_fevers)
- a26_(erysipeloid)
- a27_(leptospirosis)
- a28_(other_zoonotic_bacterial_diseases,_not_elsewhere_classified)
- a30_(leprosy_[hansen's_disease])
- a31_(infection_due_to_other_mycobacteria)
- a32_(listeriosis)
- a33_(tetanus_neonatorum)
- a35_(other_tetanus)
- a36_(diphtheria)
- a37_(whooping_cough)
- a38_(scarlet_fever)
- a39_(meningococcal_infection)
- a40_(streptococcal_septicaemia)
- a41_(other_septicaemia)
- a42_(actinomycosis)
- a43_(nocardiosis)
- a44_(bartonellosis)
- a46_(erysipelas)
- a48_(other_bacterial_diseases,_not_elsewhere_classified)
- a49_(bacterial_infection_of_unspecified_site)
- a50_(congenital_syphilis)
- a51_(early_syphilis)
- a52_(late_syphilis)
- a53_(other_and_unspecified_syphilis)
- a54_(gonococcal_infection)
- a55_(chlamydial_lymphogranuloma_(venereum))
- a56_(other_sexually_transmitted_chlamydial_diseases)
- a58_(granuloma_inguinale)
- a59_(trichomoniasis)
- a60_(anogenital_herpesviral_[herpes_simplex]_infections)
- a63_(other_predominantly_sexually_transmitted_diseases,_not_elsewhere_classified)
- a64_(unspecified_sexually_transmitted_disease)
- a66_(yaws)
- a67_(pinta_[carate])
- a68_(relapsing_fevers)
- a69_(other_spirochaetal_infections)
- a70_(chlamydia_psittaci_infection)
- a71_(trachoma)
- a74_(other_diseases_caused_by_chlamydiae)
- a75_(typhus_fever)
- a77_(spotted_fever_[tick-borne_rickettsioses])
- a78_(q_fever)
- a79_(other_rickettsioses)
- a80_(acute_poliomyelitis)
- a81_(atypical_virus_infections_of_central_nervous_system)
- a82_(rabies)
- a83_(mosquito-borne_viral_encephalitis)
- a84_(tick-borne_viral_encephalitis)
- a85_(other_viral_encephalitis,_not_elsewhere_classified)
- a86_(unspecified_viral_encephalitis)
- a87_(viral_meningitis)
- a88_(other_viral_infections_of_central_nervous_system,_not_elsewhere_classified)
- a89_(unspecified_viral_infection_of_central_nervous_system)
- a90_(dengue_fever_[classical_dengue])
- a91_(dengue_haemorrhagic_fever)
- a92_(other_mosquito-borne_viral_fevers)
- a93_(other_arthropod-borne_viral_fevers,_not_elsewhere_classified)
- a94_(unspecified_arthropod-borne_viral_fever)
- a95_(yellow_fever)
- a97_(dengue)
- a98_(other_viral_haemorrhagic_fevers,_not_elsewhere_classified)
- b00_(herpesviral_[herpes_simplex]_infections)
- b01_(varicella_[chickenpox])
- b02_(zoster_[herpes_zoster])
- b03_(smallpox)
- b05_(measles)
- b06_(rubella_[german_measles])
- b07_(viral_warts)
- b08_(other_viral_infections_characterised_by_skin_and_mucous_membrane_lesions,_not_elsewhere_classified)
- b09_(unspecified_viral_infection_characterised_by_skin_and_mucous_membrane_lesions)
- b15_(acute_hepatitis_a)
- b16_(acute_hepatitis_b)
- b17_(other_acute_viral_hepatitis)
- b18_(chronic_viral_hepatitis)
- b19_(unspecified_viral_hepatitis)
- b20_(human_immunodeficiency_virus_[hiv]_disease_resulting_in_infectious_and_parasitic_diseases)
- b21_(human_immunodeficiency_virus_[hiv]_disease_resulting_in_malignant_neoplasms)
- b22_(human_immunodeficiency_virus_[hiv]_disease_resulting_in_other_specified_diseases)
- b23_(human_immunodeficiency_virus_[hiv]_disease_resulting_in_other_conditions)
- b24_(unspecified_human_immunodeficiency_virus_[hiv]_disease)
- b25_(cytomegaloviral_disease)
- b26_(mumps)
- b27_(infectious_mononucleosis)
- b30_(viral_conjunctivitis)
- b33_(other_viral_diseases,_not_elsewhere_classified)
- b34_(viral_infection_of_unspecified_site)
- b35_(dermatophytosis)
- b36_(other_superficial_mycoses)
- b37_(candidiasis)
- b38_(coccidioidomycosis)
- b39_(histoplasmosis)
- b40_(blastomycosis)
- b42_(sporotrichosis)
- b43_(chromomycosis_and_phaeomycotic_abscess)
- b44_(aspergillosis)
- b45_(cryptococcosis)
- b46_(zygomycosis)
- b47_(mycetoma)
- b48_(other_mycoses,_not_elsewhere_classified)
- b49_(unspecified_mycosis)
- b50_(plasmodium_falciparum_malaria)
- b51_(plasmodium_vivax_malaria)
- b52_(plasmodium_malariae_malaria)
- b53_(other_parasitologically_confirmed_malaria)
- b54_(unspecified_malaria)
- b55_(leishmaniasis)
- b57_(chagas'_disease)
- b58_(toxoplasmosis)
- b59_(pneumocystosis)
- b60_(other_protozoal_diseases,_not_elsewhere_classified)
- b65_(schistosomiasis_[bilharziasis])
- b66_(other_fluke_infections)
- b67_(echinococcosis)
- b68_(taeniasis)
- b69_(cysticercosis)
- b71_(other_cestode_infections)
- b73_(onchocerciasis)
- b74_(filariasis)
- b75_(trichinellosis)
- b76_(hookworm_diseases)
- b77_(ascariasis)
- b78_(strongyloidiasis)
- b79_(trichuriasis)
- b80_(enterobiasis)
- b81_(other_intestinal_helminthiases,_not_elsewhere_classified)
- b82_(unspecified_intestinal_parasitism)
- b83_(other_helminthiases)
- b85_(pediculosis_and_phthiriasis)
- b86_(scabies)
- b87_(myiasis)
- b88_(other_infestations)
- b89_(unspecified_parasitic_disease)
- b90_(sequelae_of_tuberculosis)
- b91_(sequelae_of_poliomyelitis)
- b94_(sequelae_of_other_and_unspecified_infectious_and_parasitic_diseases)
- b95_(streptococcus_and_staphylococcus_as_the_cause_of_diseases_classified_to_other_chapters)
- b96_(other_bacterial_agents_as_the_cause_of_diseases_classified_to_other_chapters)
- b97_(viral_agents_as_the_cause_of_diseases_classified_to_other_chapters)
- b98_(other_specified_infectious_agents_as_the_cause_of_diseases_classified_to_other_chapters)
- b99_(other_and_unspecified_infectious_diseases)
