- e01_(iodine-deficiency-related_thyroid_disorders_and_allied_conditions)
- e02_(subclinical_iodine-deficiency_hypothyroidism)
- e03_(other_hypothyroidism)
- e04_(other_non-toxic_goitre)
- e05_(thyrotoxicosis_[hyperthyroidism])
- e06_(thyroiditis)
- e07_(other_disorders_of_thyroid)
- e10_(insulin-dependent_diabetes_mellitus)
- e11_(non-insulin-dependent_diabetes_mellitus)
- e12_(malnutrition-related_diabetes_mellitus)
- e13_(other_specified_diabetes_mellitus)
- e14_(unspecified_diabetes_mellitus)
- e15_(nondiabetic_hypoglycaemic_coma)
- e16_(other_disorders_of_pancreatic_internal_secretion)
- e20_(hypoparathyroidism)
- e21_(hyperparathyroidism_and_other_disorders_of_parathyroid_gland)
- e22_(hyperfunction_of_pituitary_gland)
- e23_(hypofunction_and_other_disorders_of_pituitary_gland)
- e24_(cushing's_syndrome)
- e25_(adrenogenital_disorders)
- e26_(hyperaldosteronism)
- e27_(other_disorders_of_adrenal_gland)
- e28_(ovarian_dysfunction)
- e29_(testicular_dysfunction)
- e30_(disorders_of_puberty,_not_elsewhere_classified)
- e31_(polyglandular_dysfunction)
- e32_(diseases_of_thymus)
- e34_(other_endocrine_disorders)
- e35_(disorders_of_endocrine_glands_in_diseases_classified_elsewhere)
- e41_(nutritional_marasmus)
- e43_(unspecified_severe_protein-energy_malnutrition)
- e44_(protein-energy_malnutrition_of_moderate_and_mild_degree)
- e45_(retarded_development_following_protein-energy_malnutrition)
- e46_(unspecified_protein-energy_malnutrition)
- e50_(vitamin_a_deficiency)
- e51_(thiamine_deficiency)
- e52_(niacin_deficiency_[pellagra])
- e53_(deficiency_of_other_b_group_vitamins)
- e54_(ascorbic_acid_deficiency)
- e55_(vitamin_d_deficiency)
- e56_(other_vitamin_deficiencies)
- e58_(dietary_calcium_deficiency)
- e59_(dietary_selenium_deficiency)
- e60_(dietary_zinc_deficiency)
- e61_(deficiency_of_other_nutrient_elements)
- e63_(other_nutritional_deficiencies)
- e64_(sequelae_of_malnutrition_and_other_nutritional_deficiencies)
- e65_(localised_adiposity)
- e66_(obesity)
- e67_(other_hyperalimentation)
- e68_(sequelae_of_hyperalimentation)
- e70_(disorders_of_aromatic_amino-acid_metabolism)
- e71_(disorders_of_branched-chain_amino-acid_metabolism_and_fatty-acid_metabolism)
- e72_(other_disorders_of_amino-acid_metabolism)
- e73_(lactose_intolerance)
- e74_(other_disorders_of_carbohydrate_metabolism)
- e75_(disorders_of_sphingolipid_metabolism_and_other_lipid_storage_disorders)
- e76_(disorders_of_glycosaminoglycan_metabolism)
- e77_(disorders_of_glycoprotein_metabolism)
- e78_(disorders_of_lipoprotein_metabolism_and_other_lipidaemias)
- e79_(disorders_of_purine_and_pyrimidine_metabolism)
- e80_(disorders_of_porphyrin_and_bilirubin_metabolism)
- e83_(disorders_of_mineral_metabolism)
- e84_(cystic_fibrosis)
- e85_(amyloidosis)
- e86_(volume_depletion)
- e87_(other_disorders_of_fluid,_electrolyte_and_acid-base_balance)
- e88_(other_metabolic_disorders)
- e89_(postprocedural_endocrine_and_metabolic_disorders,_not_elsewhere_classified)
