- i00_(rheumatic_fever_without_mention_of_heart_involvement)
- i01_(rheumatic_fever_with_heart_involvement)
- i02_(rheumatic_chorea)
- i05_(rheumatic_mitral_valve_diseases)
- i06_(rheumatic_aortic_valve_diseases)
- i07_(rheumatic_tricuspid_valve_diseases)
- i08_(multiple_valve_diseases)
- i09_(other_rheumatic_heart_diseases)
- i10_(essential_(primary)_hypertension)
- i11_(hypertensive_heart_disease)
- i12_(hypertensive_renal_disease)
- i13_(hypertensive_heart_and_renal_disease)
- i15_(secondary_hypertension)
- i20_(angina_pectoris)
- i21_(acute_myocardial_infarction)
- i22_(subsequent_myocardial_infarction)
- i23_(certain_current_complications_following_acute_myocardial_infarction)
- i24_(other_acute_ischaemic_heart_diseases)
- i25_(chronic_ischaemic_heart_disease)
- i26_(pulmonary_embolism)
- i27_(other_pulmonary_heart_diseases)
- i28_(other_diseases_of_pulmonary_vessels)
- i30_(acute_pericarditis)
- i31_(other_diseases_of_pericardium)
- i32_(pericarditis_in_diseases_classified_elsewhere)
- i33_(acute_and_subacute_endocarditis)
- i34_(nonrheumatic_mitral_valve_disorders)
- i35_(nonrheumatic_aortic_valve_disorders)
- i36_(nonrheumatic_tricuspid_valve_disorders)
- i37_(pulmonary_valve_disorders)
- i38_(endocarditis,_valve_unspecified)
- i39_(endocarditis_and_heart_valve_disorders_in_diseases_classified_elsewhere)
- i40_(acute_myocarditis)
- i41_(myocarditis_in_diseases_classified_elsewhere)
- i42_(cardiomyopathy)
- i43_(cardiomyopathy_in_diseases_classified_elsewhere)
- i44_(atrioventricular_and_left_bundle-branch_block)
- i45_(other_conduction_disorders)
- i46_(cardiac_arrest)
- i47_(paroxysmal_tachycardia)
- i48_(atrial_fibrillation_and_flutter)
- i49_(other_cardiac_arrhythmias)
- i50_(heart_failure)
- i51_(complications_and_ill-defined_descriptions_of_heart_disease)
- i52_(other_heart_disorders_in_diseases_classified_elsewhere)
- i60_(subarachnoid_haemorrhage)
- i61_(intracerebral_haemorrhage)
- i62_(other_nontraumatic_intracranial_haemorrhage)
- i63_(cerebral_infarction)
- i64_(stroke,_not_specified_as_haemorrhage_or_infarction)
- i65_(occlusion_and_stenosis_of_precerebral_arteries,_not_resulting_in_cerebral_infarction)
- i66_(occlusion_and_stenosis_of_cerebral_arteries,_not_resulting_in_cerebral_infarction)
- i67_(other_cerebrovascular_diseases)
- i68_(cerebrovascular_disorders_in_diseases_classified_elsewhere)
- i69_(sequelae_of_cerebrovascular_disease)
- i70_(atherosclerosis)
- i71_(aortic_aneurysm_and_dissection)
- i72_(other_aneurysm)
- i73_(other_peripheral_vascular_diseases)
- i74_(arterial_embolism_and_thrombosis)
- i77_(other_disorders_of_arteries_and_arterioles)
- i78_(diseases_of_capillaries)
- i79_(disorders_of_arteries,_arterioles_and_capillaries_in_diseases_classified_elsewhere)
- i80_(phlebitis_and_thrombophlebitis)
- i81_(portal_vein_thrombosis)
- i82_(other_venous_embolism_and_thrombosis)
- i83_(varicose_veins_of_lower_extremities)
- i84_(haemorrhoids)
- i85_(oesophageal_varices)
- i86_(varicose_veins_of_other_sites)
- i87_(other_disorders_of_veins)
- i88_(nonspecific_lymphadenitis)
- i89_(other_non-infective_disorders_of_lymphatic_vessels_and_lymph_nodes)
- i95_(hypotension)
- i97_(postprocedural_disorders_of_circulatory_system,_not_elsewhere_classified)
- i98_(other_disorders_of_circulatory_system_in_diseases_classified_elsewhere)
- i99_(other_and_unspecified_disorders_of_circulatory_system)
