- c60_malignant_neoplasm_of_penis
- c61_malignant_neoplasm_of_prostate
- c62_malignant_neoplasm_of_testis
- c63_malignant_neoplasm_of_other_and_unspecified_male_genital_organs
- n40_(hyperplasia_of_prostate)
- n41_(inflammatory_diseases_of_prostate)
- n42_(other_disorders_of_prostate)
- n43_(hydrocele_and_spermatocele)
- n44_(torsion_of_testis)
- n45_(orchitis_and_epididymitis)
- n46_(male_infertility)
- n47_(redundant_prepuce,_phimosis_and_paraphimosis)
- n48_(other_disorders_of_penis)
- n49_(inflammatory_disorders_of_male_genital_organs,_not_elsewhere_classified)
- n50_(other_disorders_of_male_genital_organs)
- n51_(disorders_of_male_genital_organs_in_diseases_classified_elsewhere)
