- heart_surgery
- coronary_angioplasty_(ptca)_+/-_stent
- other_arterial_surgery/revascularisation_procedures
- coronary_artery_bypass_grafts_(cabg)
- pacemaker/defibrillator_insertion
- heart_valve_surgery
- heart_transplant
- aortic_valve_repair/replacement
- mitral_valve_repair/replacement
- other_valve_repair/replacement
- fem-pop_bypass/leg_artery_bypass
- leg_artery_aneurysm_repair
- aortic_aneurysm/repair_or_stent
- carotid_artery_surgery/endarterectomy
- cerebral_artery_aneurysm_surgery_or_clipping
- non-coronary_artery_angioplasty_+/-_stent
- leg_artery_angioplasty_+/-_stent
- carotid_artery_angioplasty_+/-_stent
- renal_artery_angioplasty_+/-_stent
- ent_surgery
- ear_surgery
- nasal/sinus/nose_surgery
- throat/larynx_surgery_(incl_tracheostomy)
- mouth/salivary_gland_surgery
- renal/kidney_transplant
- percutaneous/open_kidney_stone_surgery/lithotripsy
- ureteric_surgery
- prostate_operation
- radical_prostatectomy
- transurethral_resection_of_prostate_(turp)
- testicular/scrotal_operation
- removal_of_testicle/orchidectomy
- vasectomy
- other_urological_surgery
- thyroid_surgery
- thyroid_radioablation_therapy
- parathyroidectomy
- adrenal_surgery
- bone_surgery/joint_surgery
- muscle/soft_tissue_surgery
- hip_replacement/revision
- knee_replacement/revision
- spine_or_back_surgery
- gynaecological_surgery
- bilateral_oophorectomy
- unilateral_oophorectomy
- hysterectomy
- hysterectomy_with_oophorectomy
- hysterectomy_with_cervical_sparing
- endometrial_ablation
- vaginal_prolapse/colposuspension
- sterilisation
- intrauterine_contraceptive_device_insertion/removal
- breast_surgery
- mastectomy
- lumpectomy
- mammoplasty/cosmetic_operation_on_breast
- venous_surgery/procedures
- hernia_surgery
- inguinal/femoral_hernia_repair
- umbilical_hernia_repair
- incisional_hernia_repair
- bladder_surgery
- transurethral_resection_bladder_tumour_(turbt)
- cystectomy
- urethral_surgery
- thyroidectomy/partial_thyroidectomy
- eye_surgery
- cataract_extraction/lens_implant
- glaucoma_surgery/trabeculectomy
- retinal_operation/vitrectomy
- bone_marrow_transplant
- reduction_or_fixation_of_bone_fracture
- amputation_of_leg
- amputation_of_foot
- amputation_of_toe
- other_amputation
- lung_removal/pneumonectomy/lobectomy
- bullaectomy/bullae_removal
- lung_transplant
- other_thoracic_surgery
- stomach_surgery
- oesophageal_surgery
- liver_surgery
- biliary_surgery
- pancreas_surgery
- splenectomy
- liver_transplant
- cholecystectomy/gall_bladder_removal
- bile_duct_surgery
- pancreatic_transplant
- appendicectomy
- bowel_resection
- anal_surgery
- large_bowel_resection_+/-_colostomy
- small_bowel_resection
- rectal_or_colon_polypectomy
- colectomy/hemicolectomy
- rectal/sigmoid_resection
- other_bowel_surgery
- brain_surgery
- intracranial_haematoma_drainage
- cerebroventricular_shunt/shunt_for_hydrocephalus
- spinal_cord_surgery
- peripheral_nerve_surgery
- pituitary_surgery
- pituitary_transplant
- skin_operation_or_plastic_surgery
- fertility_treatment_procedures
- fistula_for_dialysis
- caesarean_section_/_caesarian_section
- tonsillectomy_+/-_adenoids
- varicose_vein_surgery
- wisdom_teeth_surgery
- maxillo-facial_surgery
- oesphageal_fundoplication/hiatus_hernia_surgery
- haemorroidectomy_/_piles_surgery/_banding_of_piles
- pilonidal_sinus_surgery_(anal)
- abdominal/pelvic_adhesion_surgery
- laparotomy_nos
- nephrectomy/kidney_removed
- anterior/posterior_repair_bladder/uterus
- testicular_hydrocoele_surgery_/_drainage
- male_circumcision
- squint_correction
- spinal_laminectomy
- arthroscopy_nos
- foot_surgery
- lower_limb_surgery
- knee_surgery_(not_replacement)
- hip_surgery_(not_replacement)
- upper_limb_surgery
- shoulder_surgery
- elbow_surgery
- carpal_tunnel_surgery
- cruciate_ligament_surgery
- bunion/hallus_valgus_surgery
- removal_of_mole/skin_lesion
- ovarian/tubal_surgery
- ovarian_cyst_removal/surgery
- ectopic_pregnancy_surgery
- uterine_surgery
- myomectomy/fibroids_removed
- dilatation_and_curettage/d+c
- cervix_surgery
- cone_biopsy
- breast_cyst/abscess_removal
- coronary_angiogram
- angiogram_not_coronary
- echocardiogram/transoesophageal_echo
- endoscopy_/_gastroscopy
- ercp/endoscopic_retrograde_cholangiopancreatogram
- colonoscopy/sigmoidoscopy
- laparoscopy
- hysteroscopy_+/-_biopsy
- colposcopy_+/-_biopsy
- triple_heart_bypass
- cardioversion
- mastoidectomy/mastoid_surgery
- stapedectomy
- dental/tooth_surgery
- gallstones_removed
- duodenal_surgery
- ileostomy/colostomy_surgery
- discectomy
- ankle_surgery
- achilles_tendon_repair
- hand/finger_surgery
- dupuytren's_contracture_surgery
- lipoma_removed_/_excision_of_lipoma
- lymph_node_surgery
- salpingectomy
- uterine_polypectomy/uterine_polyps_removed
- termination_of_pregnancy/top
- cervical_polyps_removed
- laser_treatment_cervix
- pelvic_floor_surgery
- breast_biopsy
- ecg/electrocardiogram
- bronchoscopy
- cystoscopy
- pacemaker_insertion
- pacemaker_battery_change
- defibrillator/icd_insertion
- defibrillator/icd_battery_change
- electrophysiological_studies_(eps)
- cardiac_ablation
- pericardial_surgery
- femoral/popliteal/iliac_aneurysm_repair
- tympanic_membrane_surgery_/_ear_drum_repair
- rhinoplasty_/_nose_surgery
- sinus_surgery
- nasal_polyp_surgery_/_nasal_polypectomy
- parotid_surgery_/_parotidectomy
- tonsillectomy_/_tonsil_surgery
- adenoid_surgery_/_adenoidectomy
- inguinal_hernia_repair
- femoral_hernia_repair
- gastrectomy
- peptic_ulcer_surgery
- gastric_ulcer_surgery
- duodenal_ulcer_surgery
- ileostomy_surgery
- ileostomy_formation
- ileostomy_reversal
- surgery_for_pyloric_stenosis
- colostomy_surgery
- colostomy_formation
- colostomy_reversal
- anterior_resection
- abdomino-perineal_resection_/_ap_resection
- anal_fissure_surgery
- dialysis_access_surgery
- haemodialysis_access_/_fistula_surgery
- peritoneal_dialysis_(capd)_access_surgery
- urethral_stricture_surgery_/_dilatation
- testicular_lump_removal
- varicocoele_/_varicocele_surgery
- removal_of_epididymal_cyst
- orchidopexy
- reversal_of_vasectomy_/_vasectomy_reversal
- spinal_fusion
- eyelid_surgery
- nasolacrimal_/_tear_duct_surgery
- removal_of_malignant_melanoma
- removal_of_benign_skin_lesion
- removal_of_squamous_cell_carcinoma_(scc)
- removal_of_rodent_ulcer_/_basal_cell_carcinoma_(bcc)
- skin_graft
- nail_surgery_/_nail_removal
- exercise_ecg
- mri_/_magnetic_resonance_imaging
- laryngoscopy
- nasal_endoscopy
- scan_/_x-ray
- cardiac_investigation
- gastrointestinal_investigation
- genito-urinary_investigation
- ct_scan
- bone_scan
- ultrasound_scan
- pet_scan
- barium_meal_/_barium_swallow
- barium_enema
- ct_colonoscopy
- biopsy
- bone_marrow_biopsy
- liver_biopsy
- prostate_biopsy
- renal_biopsy_/_kidney_biopsy
- lung_biopsy
- lumbar_puncture
- cystoscopy_copy
