- antacids_and_simeticone
- compound_alginates&prop_indigestion_prep
- antispasmod.&other_drgs_alt.gut_motility
- test_for_helicobacter_pylori
- h2-receptor_antagonists
- selective_antimuscarinics
- chelates_and_complexes
- prostaglandin_analogues
- proton_pump_inhibitors
- other_ulcer-healing_drugs
- adsorbents_and_bulk-forming_drugs
- antimotility_drugs
- enkephalinase_inhibitors
- tryptophan_hydroxylase_inhibitors
- chronic_bowel_disorders
- aminosalicylates
- corticosteroids
- drugs_affecting_immune_response
- food_allergy
- bulk-forming_laxatives
- stimulant_laxatives
- faecal_softeners
- osmotic_laxatives
- bowel_cleansing_preparations
- peripheral_opioid-receptor_antagonists
- other_drugs_used_in_constipation
- soothing_haemorrhoidal_preparations
- co_haemorrhoidal_prep's_+_corticosteroid
- rectal_sclerosants
- management_of_anal_fissures
- local_care_of_stoma
- drugs_affecting_biliary_composition&flow
- bile_acid_sequestrants
- pancreatin
- cardiac_glycosides
- phosphodiesterase_type-3_inhibitors
- thiazides_and_related_diuretics
- loop_diuretics
- pot-sparing_diuretics&aldosterone_antag
- potassium_sparing_diuretics_&_compounds
- osmotic_diuretics
- diuretics_with_potassium
- drugs_for__arrhythmias
- beta-adrenoceptor_blocking_drugs
- vasodilator_antihypertensive_drugs
- centrally-acting_antihypertensive_drugs
- adrenergic_neurone_blocking_drugs
- alpha-adrenoceptor_blocking_drugs
- angiotensin-converting_enzyme_inhibitors
- ganglion-blocking_drugs
- other_adrenergic_neurone_blocking_drugs
- nitrates
- calcium-channel_blockers
- other_antianginal_drugs
- peripheral_vasodilators_&_related_drugs
- flosequinan
- other_vasodilators_for_angina
- inotropic_sympathomimetics
- vasoconstrictor_sympathomimetics
- cardiopulmonary_resuscitation
- parenteral_anticoagulants
- oral_anticoagulants
- protamine_sulfate
- idarucizumab
- antiplatelet_drugs
- fibrinolytic_drugs
- antifibrinolytic_drugs_&_haemostatics
- lipid-regulating_drugs
- local_sclerosants
- selective_beta(2)-agonists
- antimuscarinic_bronchodilators
- theophylline
- compound_bronchodilator_preparations
- corticosteroids_(respiratory)
- cromoglycate_and_related_therapy
- leukotriene_receptor_antagonists
- phosphodiesterase_type-4_inhibitors
- antihistamines
- allergen_immunotherapy
- allergic_emergencies
- respiratory_stimulants
- oxygen
- mucolytics
- aromatic_inhalations
- cough_suppressants
- expectorant_&_demulcent_cough_prep's
- systemic_nasal_decongestants
- antifibrotics
- hypnotics
- anxiolytics
- barbiturates
- antipsychotic_drugs
- antipsychotic_depot_injections
- drugs_used_for_mania_and_hypomania
- tricyclic_&_related_antidepressant_drugs
- monoamine-oxidase_inhibitors_(maois)
- selective_serotonin_re-uptake_inhibitors
- cns_stimulants_and_drugs_used_for_adhd
- gastro-intestinal_anti-obesity_drugs
- centrally-acting_appetite_suppressants
- drugs_used_in_nausea_and_vertigo
- non-opioid_analgesics_and_compound_prep
- opioid_analgesics
- neuropathic_pain
- treatment_of_acute_migraine
- control_of_epilepsy
- drugs_used_in_status_epilepticus
- dopaminergic_drugs_used_in_parkinsonism
- antimuscarinic_drugs_used_in_parkin'ism
- essentialtremor,chorea,tics&reldisorders
- alcohol_dependence
- nicotine_dependence
- opioid_dependence
- drugs_for_dementia
- benzylpenicillin&phenoxymethylpenicillin
- cephalosporins_and_other_beta-lactams
- tetracyclines
- aminoglycosides
- macrolides
- clindamycin_and_lincomycin
- some_other_antibacterials
- sulfonamides_and_trimethoprim
- antituberculosis_drugs
- antileprotic_drugs
- metronidazole,_tinidazole_&_ornidazole
- quinolones
- urinary-tract_infections
- antifungal_drugs
- triazole_antifungals
- imidazole_antifungals
- polyene_antifungals
- echinocandin_antifungals
- other_antifungals
- antiviral_drugs
- hiv_infection
- herpes_simplex_and_varicella-zoster
- chronic_hepatitis_b
- influenza
- respiratory_syncytial_virus
- antimalarials
- amoebicides
- trichomonacides
- antigiardial_drugs
- leishmaniacides
- trypanocides
- drugs_for_pneumocystis_pneumonia
- drugs_for_threadworms
- ascaricides
- drugs_for_tapeworm_infections
- drugs_for_hookworms
- schistosomicides
- filaricides
- drugs_for_strongyloidiasis
- sulfonylureas
- treatment_of_hypoglycaemia
- diabetic_nephropathy_&_neuropathy
- diabetic_diagnostic_&_monitoring_agents
- thyroid_hormones
- antithyroid_drugs
- replacement_therapy
- use_of_corticosteroids
- oestrogens_and_hrt
- male_sex_hormones_and_antagonists
- anabolic_steroids
- hypothalamic&ant_pituit_hormone&antioest
- posterior_pituitary_hormones&antagonists
- calcitonin_and_parathyroid_hormone
- bisphosphonates_and_other_drugs
- bromocriptine_&_other_dopaminergic_drugs
- drugs_affecting_gonadotrophins
- metyrapone
- somatomedins
- prostaglandins_and_oxytocics
- mifepristone
- myometrial_relaxants
- preparations_for_vaginal/vulval_changes
- vaginal_and_vulval_infections
- combined_hormonal_contraceptives
- oral_progestogen-only_contraceptives
- spermicidal_contraceptives
- emergency_contraception
- drugs_for_urinary_retention
- drugs/urin'y_frequ'cy_enuresis_&_incont
- drugs_used_in_urological_pain
- bladder_instillations/urological_surgery
- drugs_for_erectile_dysfunction
- drugs_for_premature_ejaculation
- drugs_for_cytotoxic-induced_side-effects
- alkylating_drugs
- anthracyclines_&_cytotoxic_antibiotics
- antimetabolites
- vinca_alkaloids_and_etoposide
- other_antineoplastic_drugs
- other_cytotoxic_drugs
- antiproliferative_immunosuppressants
- cortico'oids_&_other_immunosuppressants
- anti-lymphocyte_monoclonal_antibodies
- other_immunomodulating_drugs
- oestrogens
- progestogens
- androgens
- breast_cancer
- oral_iron
- drugs_used_in_megaloblastic_anaemias
- hypoplastic/haemolytic_&_renal_anaemias
- drugs_used_in_platelet_disorders
- drugs_used_in_neutropenia
- drugs_used_to_mobilise_stem_cells
- oral_potassium
- electrolytes_and_water
- intravenous_nutrition
- foods_for_special_diets
- enteral_nutrition
- calcium_supplements
- phosphate_supplements
- fluoride
- zinc
- selenium
- vitamin_a
- cyanocobalamin_(b12)
- vitamin_c_(ascorbic_acid)
- vitamin_d
- vitamin_e
- vitamin_k
- multivitamin_preparations
- other_vitamin_formulations
- bitters_and_tonics
- drugs_used_in_metabolic_disorders
- acute_porphyrias
- foods
- compound_vit/mineral_formulations
- amino_acids_&_nutritional_agents
- enzymes
- glandular
- digestive_aids
- other_health_supplements
- non-steroidal_anti-inflammatory_drugs
- local_corticosteroid_injections
- rheumatic_disease_suppressant_drugs
- gout_&_cytotoxic_induced_hyperiuicaemia
- other_drugs_for_rheumatic_diseases
- dgs_which_enhance_neuromus'ar_transmi'on
- skeletal_muscle_relaxants
- rubefacients,top_nsaids,capsaicin_&_poul
- antibacterials
- antifungals
- antivirals
- other_anti-inflammatory_preparations
- mydriatics_and_cycloplegics
- treatment_of_glaucoma
- local_anaesthetics
- tear_deficiency,eye_lubricant/astringent
- ocular_diagnos/peri-op_prepn&photodyn_tt
- other_eye_preparations
- preparations_for_cataracts
- contact_lenses
- otitis_externa
- otitis_media
- removal_of_ear_wax_&_other_substances
- drugs_used_in_nasal_allergy
- topical_nasal_decongestants
- nasal_prepn_for_infection
- drugs_for_oral_ulceration_&_inflammation
- oropharyngeal_anti-infective_drugs
- lozenges_&_sprays
- mouth-washes,_gargles,_and_dentifrices
- treatment_of_dry_mouth
- vehicles
- emollients
- barrier_preparations
- dusting-powders
- top_local_anaesthetics_&_antipruritics
- topical_corticosteroids
- preparations_for_eczema_and_psoriasis
- preparations_for_eczema
- preparations_for_psoriasis
- drugs_affecting_the_immune_response
- preparations_for_acne
- topical_preparations_for_acne
- oral_preparations_for_acne
- topical_preparation_for_rosacea
- preparations_for_warts_and_calluses
- sunscreening_preparations
- camouflagers
- shampoos_and_some_other_scalp_prep's
- antibacterial_preps_only_used_topically
- antifungal_preparations
- antiviral_preparations
- parasiticidal_preparations
- prep's_for_minor_cuts_&_abrasions
- alcohols_&_saline
- chlorhexidine_salts
- cationic_surfactants_&_soaps
- chlorine_&_iodine
- phenolics
- oxidisers_&_dyes
- desloughing_agents
- antiperspirants
- medicated_stockings
- surgical_adhesive_removers
- gel_and_colloid_dressings
- topical_circulatory_preparations
- miscellaneous_topical_preparations
- diagnostic_vaccines
- vaccines_and_antisera
- other_immunoglobulins
- normal_immunoglobulin
- disease-specific_immunoglobulins
- anti-d_(rho)_immunoglobulin
- intravenous_anaesthetics
- inhalational_anaesthetics
- antimuscarinic_drugs
- benzodiazepines
- neuromuscular_blocking_drugs
- anticholinesterases_used_in_anaesthesia
- antagonists_for_respiratory_depression
- drugs_for_malignant_hyperthermia
- adjuncts_to_intractable_pain_spasticity
- urine_testing_reagents
- x-ray_contrast_media
- diagnostic_agents
- special_sanction_reagents
- alcohol,_wines_&_spirits
- individually_formulated_preps-bought_in
- individ_formulated_preps-prepared_extemp
- homeopathic_preparations
- household_&_other_over_the_counter_lines
- poisoning_antidotes
- adjuncts_to_dispensing
- single_substances
- other_preparations
- acids
- concentrated_waters
- essences
- extracts
- infusions
- oils
- tinctures
- syrups
- base/dil/susp_agents/stabilisers
- colouring,flavouring_&_sweetening_agents
- disinfectants,preserv&sterilising_agents
- polysorbates_&_tween
- lubricating_jellies/pessaries
- electrode/ultrasonic_gels
- cordials/soft_drinks
- sterile_water
- purified_water
- tap_water
- spring/mineral_&_soda_waters
- other_gases
