- f00_(dementia_in_alzheimer's_disease)
- f01_(vascular_dementia)
- f02_(dementia_in_other_diseases_classified_elsewhere)
- f03_(unspecified_dementia)
- f04_(organic_amnesic_syndrome,_not_induced_by_alcohol_and_other_psychoactive_substances)
- f05_(delirium,_not_induced_by_alcohol_and_other_psychoactive_substances)
- f06_(other_mental_disorders_due_to_brain_damage_and_dysfunction_and_to_physical_disease)
- f07_(personality_and_behavioural_disorders_due_to_brain_disease,_damage_and_dysfunction)
- f09_(unspecified_organic_or_symptomatic_mental_disorder)
- f10_(mental_and_behavioural_disorders_due_to_use_of_alcohol)
- f11_(mental_and_behavioural_disorders_due_to_use_of_opioids)
- f12_(mental_and_behavioural_disorders_due_to_use_of_cannabinoids)
- f13_(mental_and_behavioural_disorders_due_to_use_of_sedatives_or_hypnotics)
- f14_(mental_and_behavioural_disorders_due_to_use_of_cocaine)
- f15_(mental_and_behavioural_disorders_due_to_use_of_other_stimulants,_including_caffeine)
- f16_(mental_and_behavioural_disorders_due_to_use_of_hallucinogens)
- f17_(mental_and_behavioural_disorders_due_to_use_of_tobacco)
- f18_(mental_and_behavioural_disorders_due_to_use_of_volatile_solvents)
- f19_(mental_and_behavioural_disorders_due_to_multiple_drug_use_and_use_of_other_psychoactive_substances)
- f20_(schizophrenia)
- f21_(schizotypal_disorder)
- f22_(persistent_delusional_disorders)
- f23_(acute_and_transient_psychotic_disorders)
- f24_(induced_delusional_disorder)
- f25_(schizoaffective_disorders)
- f28_(other_nonorganic_psychotic_disorders)
- f29_(unspecified_nonorganic_psychosis)
- f30_(manic_episode)
- f31_(bipolar_affective_disorder)
- f32_(depressive_episode)
- f33_(recurrent_depressive_disorder)
- f34_(persistent_mood_[affective]_disorders)
- f38_(other_mood_[affective]_disorders)
- f39_(unspecified_mood_[affective]_disorder)
- f40_(phobic_anxiety_disorders)
- f41_(other_anxiety_disorders)
- f42_(obsessive-compulsive_disorder)
- f43_(reaction_to_severe_stress,_and_adjustment_disorders)
- f44_(dissociative_[conversion]_disorders)
- f45_(somatoform_disorders)
- f48_(other_neurotic_disorders)
- f50_(eating_disorders)
- f51_(nonorganic_sleep_disorders)
- f52_(sexual_dysfunction,_not_caused_by_organic_disorder_or_disease)
- f53_(mental_and_behavioural_disorders_associated_with_the_puerperium,_not_elsewhere_classified)
- f54_(psychological_and_behavioural_factors_associated_with_disorders_or_diseases_classified_elsewhere)
- f55_(abuse_of_non-dependence-producing_substances)
- f59_(unspecified_behavioural_syndromes_associated_with_physiological_disturbances_and_physical_factors)
- f60_(specific_personality_disorders)
- f61_(mixed_and_other_personality_disorders)
- f62_(enduring_personality_changes,_not_attributable_to_brain_damage_and_disease)
- f63_(habit_and_impulse_disorders)
- f64_(gender_identity_disorders)
- f65_(disorders_of_sexual_preference)
- f66_(psychological_and_behavioural_disorders_associated_with_sexual_development_and_orientation)
- f68_(other_disorders_of_adult_personality_and_behaviour)
- f69_(unspecified_disorder_of_adult_personality_and_behaviour)
- f70_(mild_mental_retardation)
- f71_(moderate_mental_retardation)
- f72_(severe_mental_retardation)
- f78_(other_mental_retardation)
- f79_(unspecified_mental_retardation)
- f80_(specific_developmental_disorders_of_speech_and_language)
- f81_(specific_developmental_disorders_of_scholastic_skills)
- f82_(specific_developmental_disorder_of_motor_function)
- f83_(mixed_specific_developmental_disorders)
- f84_(pervasive_developmental_disorders)
- f88_(other_disorders_of_psychological_development)
- f89_(unspecified_disorder_of_psychological_development)
- f90_(hyperkinetic_disorders)
- f91_(conduct_disorders)
- f92_(mixed_disorders_of_conduct_and_emotions)
- f93_(emotional_disorders_with_onset_specific_to_childhood)
- f94_(disorders_of_social_functioning_with_onset_specific_to_childhood_and_adolescence)
- f95_(tic_disorders)
- f98_(other_behavioural_and_emotional_disorders_with_onset_usually_occurring_in_childhood_and_adolescence)
- f99_(mental_disorder,_not_otherwise_specified)
