- g00_(bacterial_meningitis,_not_elsewhere_classified)
- g01_(meningitis_in_bacterial_diseases_classified_elsewhere)
- g02_(meningitis_in_other_infectious_and_parasitic_diseases_classified_elsewhere)
- g03_(meningitis_due_to_other_and_unspecified_causes)
- g04_(encephalitis,_myelitis_and_encephalomyelitis)
- g05_(encephalitis,_myelitis_and_encephalomyelitis_in_diseases_classified_elsewhere)
- g06_(intracranial_and_intraspinal_abscess_and_granuloma)
- g07_(intracranial_and_intraspinal_abscess_and_granuloma_in_diseases_classified_elsewhere)
- g08_(intracranial_and_intraspinal_phlebitis_and_thrombophlebitis)
- g09_(sequelae_of_inflammatory_diseases_of_central_nervous_system)
- g10_(huntington's_disease)
- g11_(hereditary_ataxia)
- g12_(spinal_muscular_atrophy_and_related_syndromes)
- g13_(systemic_atrophies_primarily_affecting_central_nervous_system_in_diseases_classified_elsewhere)
- g14_(postpolio_syndrome)
- g20_(parkinson's_disease)
- g21_(secondary_parkinsonism)
- g22_(parkinsonism_in_diseases_classified_elsewhere)
- g23_(other_degenerative_diseases_of_basal_ganglia)
- g24_(dystonia)
- g25_(other_extrapyramidal_and_movement_disorders)
- g30_(alzheimer's_disease)
- g31_(other_degenerative_diseases_of_nervous_system,_not_elsewhere_classified)
- g32_(other_degenerative_disorders_of_nervous_system_in_diseases_classified_elsewhere)
- g35_(multiple_sclerosis)
- g36_(other_acute_disseminated_demyelination)
- g37_(other_demyelinating_diseases_of_central_nervous_system)
- g40_(epilepsy)
- g41_(status_epilepticus)
- g43_(migraine)
- g44_(other_headache_syndromes)
- g45_(transient_cerebral_ischaemic_attacks_and_related_syndromes)
- g46_(vascular_syndromes_of_brain_in_cerebrovascular_diseases)
- g47_(sleep_disorders)
- g50_(disorders_of_trigeminal_nerve)
- g51_(facial_nerve_disorders)
- g52_(disorders_of_other_cranial_nerves)
- g53_(cranial_nerve_disorders_in_diseases_classified_elsewhere)
- g54_(nerve_root_and_plexus_disorders)
- g55_(nerve_root_and_plexus_compressions_in_diseases_classified_elsewhere)
- g56_(mononeuropathies_of_upper_limb)
- g57_(mononeuropathies_of_lower_limb)
- g58_(other_mononeuropathies)
- g59_(mononeuropathy_in_diseases_classified_elsewhere)
- g60_(hereditary_and_idiopathic_neuropathy)
- g61_(inflammatory_polyneuropathy)
- g62_(other_polyneuropathies)
- g63_(polyneuropathy_in_diseases_classified_elsewhere)
- g64_(other_disorders_of_peripheral_nervous_system)
- g70_(myasthenia_gravis_and_other_myoneural_disorders)
- g71_(primary_disorders_of_muscles)
- g72_(other_myopathies)
- g73_(disorders_of_myoneural_junction_and_muscle_in_diseases_classified_elsewhere)
- g80_(infantile_cerebral_palsy)
- g81_(hemiplegia)
- g82_(paraplegia_and_tetraplegia)
- g83_(other_paralytic_syndromes)
- g90_(disorders_of_autonomic_nervous_system)
- g91_(hydrocephalus)
- g92_(toxic_encephalopathy)
- g93_(other_disorders_of_brain)
- g94_(other_disorders_of_brain_in_diseases_classified_elsewhere)
- g95_(other_diseases_of_spinal_cord)
- g96_(other_disorders_of_central_nervous_system)
- g97_(postprocedural_disorders_of_nervous_system,_not_elsewhere_classified)
- g98_(other_disorders_of_nervous_system,_not_elsewhere_classified)
- g99_(other_disorders_of_nervous_system_in_diseases_classified_elsewhere)
