- h00_(hordeolum_and_chalazion)
- h01_(other_inflammation_of_eyelid)
- h02_(other_disorders_of_eyelid)
- h03_(disorders_of_eyelid_in_diseases_classified_elsewhere)
- h04_(disorders_of_lachrymal_system)
- h05_(disorders_of_orbit)
- h06_(disorders_of_lachrymal_system_and_orbit_in_diseases_classified_elsewhere)
- h10_(conjunctivitis)
- h11_(other_disorders_of_conjunctiva)
- h13_(disorders_of_conjunctiva_in_diseases_classified_elsewhere)
- h15_(disorders_of_sclera)
- h16_(keratitis)
- h17_(corneal_scars_and_opacities)
- h18_(other_disorders_of_cornea)
- h19_(disorders_of_sclera_and_cornea_in_diseases_classified_elsewhere)
- h20_(iridocyclitis)
- h21_(other_disorders_of_iris_and_ciliary_body)
- h22_(disorders_of_iris_and_ciliary_body_in_diseases_classified_elsewhere)
- h25_(senile_cataract)
- h26_(other_cataract)
- h27_(other_disorders_of_lens)
- h28_(cataract_and_other_disorders_of_lens_in_diseases_classified_elsewhere)
- h30_(chorioretinal_inflammation)
- h31_(other_disorders_of_choroid)
- h32_(chorioretinal_disorders_in_diseases_classified_elsewhere)
- h33_(retinal_detachments_and_breaks)
- h34_(retinal_vascular_occlusions)
- h35_(other_retinal_disorders)
- h36_(retinal_disorders_in_diseases_classified_elsewhere)
- h40_(glaucoma)
- h42_(glaucoma_in_diseases_classified_elsewhere)
- h43_(disorders_of_vitreous_body)
- h44_(disorders_of_globe)
- h45_(disorders_of_vitreous_body_and_globe_in_diseases_classified_elsewhere)
- h46_(optic_neuritis)
- h47_(other_disorders_of_optic_[2nd]_nerve_and_visual_pathways)
- h48_(disorders_of_optic_[2nd]_nerve_and_visual_pathways_in_diseases_classified_elsewhere)
- h49_(paralytic_strabismus)
- h50_(other_strabismus)
- h51_(other_disorders_of_binocular_movement)
- h52_(disorders_of_refraction_and_accommodation)
- h53_(visual_disturbances)
- h54_(blindness_and_low_vision)
- h55_(nystagmus_and_other_irregular_eye_movements)
- h57_(other_disorders_of_eye_and_adnexa)
- h58_(other_disorders_of_eye_and_adnexa_in_diseases_classified_elsewhere)
- h59_(postprocedural_disorders_of_eye_and_adnexa,_not_elsewhere_classified)
