- l00_(staphylococcal_scalded_skin_syndrome)
- l01_(impetigo)
- l02_(cutaneous_abscess,_furuncle_and_carbuncle)
- l03_(cellulitis)
- l04_(acute_lymphadenitis)
- l05_(pilonidal_cyst)
- l08_(other_local_infections_of_skin_and_subcutaneous_tissue)
- l10_(pemphigus)
- l11_(other_acantholytic_disorders)
- l12_(pemphigoid)
- l13_(other_bullous_disorders)
- l14_(bullous_disorders_in_diseases_classified_elsewhere)
- l20_(atopic_dermatitis)
- l21_(seborrhoeic_dermatitis)
- l22_(diaper_[napkin]_dermatitis)
- l23_(allergic_contact_dermatitis)
- l24_(irritant_contact_dermatitis)
- l25_(unspecified_contact_dermatitis)
- l26_(exfoliative_dermatitis)
- l27_(dermatitis_due_to_substances_taken_internally)
- l28_(lichen_simplex_chronicus_and_prurigo)
- l29_(pruritus)
- l30_(other_dermatitis)
- l40_(psoriasis)
- l41_(parapsoriasis)
- l42_(pityriasis_rosea)
- l43_(lichen_planus)
- l44_(other_papulosquamous_disorders)
- l50_(urticaria)
- l51_(erythema_multiforme)
- l52_(erythema_nodosum)
- l53_(other_erythematous_conditions)
- l54_(erythema_in_diseases_classified_elsewhere)
- l55_(sunburn)
- l56_(other_acute_skin_changes_due_to_ultraviolet_radiation)
- l57_(skin_changes_due_to_chronic_exposure_to_nonionising_radiation)
- l58_(radiodermatitis)
- l59_(other_disorders_of_skin_and_subcutaneous_tissue_related_to_radiation)
- l60_(nail_disorders)
- l62_(nail_disorders_in_diseases_classified_elsewhere)
- l63_(alopecia_areata)
- l64_(androgenic_alopecia)
- l65_(other_nonscarring_hair_loss)
- l66_(cicatricial_alopecia_[scarring_hair_loss])
- l67_(hair_colour_and_hair_shaft_abnormalities)
- l68_(hypertrichosis)
- l70_(acne)
- l71_(rosacea)
- l72_(follicular_cysts_of_skin_and_subcutaneous_tissue)
- l73_(other_follicular_disorders)
- l74_(eccrine_sweat_disorders)
- l75_(apocrine_sweat_disorders)
- l80_(vitiligo)
- l81_(other_disorders_of_pigmentation)
- l82_(seborrhoeic_keratosis)
- l83_(acanthosis_nigricans)
- l84_(corns_and_callosities)
- l85_(other_epidermal_thickening)
- l86_(keratoderma_in_diseases_classified_elsewhere)
- l87_(transepidermal_elimination_disorders)
- l88_(pyoderma_gangrenosum)
- l89_(decubitus_ulcer)
- l90_(atrophic_disorders_of_skin)
- l91_(hypertrophic_disorders_of_skin)
- l92_(granulomatous_disorders_of_skin_and_subcutaneous_tissue)
- l93_(lupus_erythematosus)
- l94_(other_localised_connective_tissue_disorders)
- l95_(vasculitis_limited_to_skin,_not_elsewhere_classified)
- l97_(ulcer_of_lower_limb,_not_elsewhere_classified)
- l98_(other_disorders_of_skin_and_subcutaneous_tissue,_not_elsewhere_classified)
- l99_(other_disorders_of_skin_and_subcutaneous_tissue_in_diseases_classified_elsewhere)
