- n00_(acute_nephritic_syndrome)
- n01_(rapidly_progressive_nephritic_syndrome)
- n02_(recurrent_and_persistent_haematuria)
- n03_(chronic_nephritic_syndrome)
- n04_(nephrotic_syndrome)
- n05_(unspecified_nephritic_syndrome)
- n06_(isolated_proteinuria_with_specified_morphological_lesion)
- n07_(hereditary_nephropathy,_not_elsewhere_classified)
- n08_(glomerular_disorders_in_diseases_classified_elsewhere)
- n10_(acute_tubulo-interstitial_nephritis)
- n11_(chronic_tubulo-interstitial_nephritis)
- n12_(tubulo-interstitial_nephritis,_not_specified_as_acute_or_chronic)
- n13_(obstructive_and_reflux_uropathy)
- n14_(drug-_and_heavy-metal-induced_tubulo-interstitial_and_tubular_conditions)
- n15_(other_renal_tubulo-interstitial_diseases)
- n16_(renal_tubulo-interstitial_disorders_in_diseases_classified_elsewhere)
- n17_(acute_renal_failure)
- n18_(chronic_renal_failure)
- n19_(unspecified_renal_failure)
- n20_(calculus_of_kidney_and_ureter)
- n21_(calculus_of_lower_urinary_tract)
- n22_(calculus_of_urinary_tract_in_diseases_classified_elsewhere)
- n23_(unspecified_renal_colic)
- n25_(disorders_resulting_from_impaired_renal_tubular_function)
- n26_(unspecified_contracted_kidney)
- n27_(small_kidney_of_unknown_cause)
- n28_(other_disorders_of_kidney_and_ureter,_not_elsewhere_classified)
- n29_(other_disorders_of_kidney_and_ureter_in_diseases_classified_elsewhere)
- n30_(cystitis)
- n31_(neuromuscular_dysfunction_of_bladder,_not_elsewhere_classified)
- n32_(other_disorders_of_bladder)
- n33_(bladder_disorders_in_diseases_classified_elsewhere)
- n34_(urethritis_and_urethral_syndrome)
- n35_(urethral_stricture)
- n36_(other_disorders_of_urethra)
- n37_(urethral_disorders_in_diseases_classified_elsewhere)
- n39_(other_disorders_of_urinary_system)
- n40_(hyperplasia_of_prostate)
- n41_(inflammatory_diseases_of_prostate)
- n42_(other_disorders_of_prostate)
- n43_(hydrocele_and_spermatocele)
- n44_(torsion_of_testis)
- n45_(orchitis_and_epididymitis)
- n46_(male_infertility)
- n47_(redundant_prepuce,_phimosis_and_paraphimosis)
- n48_(other_disorders_of_penis)
- n49_(inflammatory_disorders_of_male_genital_organs,_not_elsewhere_classified)
- n50_(other_disorders_of_male_genital_organs)
- n51_(disorders_of_male_genital_organs_in_diseases_classified_elsewhere)
- n60_(benign_mammary_dysplasia)
- n61_(inflammatory_disorders_of_breast)
- n62_(hypertrophy_of_breast)
- n63_(unspecified_lump_in_breast)
- n64_(other_disorders_of_breast)
- n70_(salpingitis_and_oophoritis)
- n71_(inflammatory_disease_of_uterus,_except_cervix)
- n72_(inflammatory_disease_of_cervix_uteri)
- n73_(other_female_pelvic_inflammatory_diseases)
- n74_(female_pelvic_inflammatory_disorders_in_diseases_classified_elsewhere)
- n75_(diseases_of_bartholin's_gland)
- n76_(other_inflammation_of_vagina_and_vulva)
- n77_(vulvovaginal_ulceration_and_inflammation_in_diseases_classified_elsewhere)
- n80_(endometriosis)
- n81_(female_genital_prolapse)
- n82_(fistulae_involving_female_genital_tract)
- n83_(noninflammatory_disorders_of_ovary,_fallopian_tube_and_broad_ligament)
- n84_(polyp_of_female_genital_tract)
- n85_(other_noninflammatory_disorders_of_uterus,_except_cervix)
- n86_(erosion_and_ectropion_of_cervix_uteri)
- n87_(dysplasia_of_cervix_uteri)
- n88_(other_noninflammatory_disorders_of_cervix_uteri)
- n89_(other_noninflammatory_disorders_of_vagina)
- n90_(other_noninflammatory_disorders_of_vulva_and_perineum)
- n91_(absent,_scanty_and_rare_menstruation)
- n92_(excessive,_frequent_and_irregular_menstruation)
- n93_(other_abnormal_uterine_and_vaginal_bleeding)
- n94_(pain_and_other_conditions_associated_with_female_genital_organs_and_menstrual_cycle)
- n95_(menopausal_and_other_perimenopausal_disorders)
- n96_(habitual_aborter)
- n97_(female_infertility)
- n98_(complications_associated_with_artificial_fertilisation)
- n99_(postprocedural_disorders_of_genito-urinary_system,_not_elsewhere_classified)
