- q00_(anencephaly_and_similar_malformations)
- q01_(encephalocele)
- q02_(microcephaly)
- q03_(congenital_hydrocephalus)
- q04_(other_congenital_malformations_of_brain)
- q05_(spina_bifida)
- q06_(other_congenital_malformations_of_spinal_cord)
- q07_(other_congenital_malformations_of_nervous_system)
- q10_(congenital_malformations_of_eyelid,_lachrymal_apparatus_and_orbit)
- q11_(anophthalmos,_microphthalmos_and_macrophthalmos)
- q12_(congenital_lens_malformations)
- q13_(congenital_malformations_of_anterior_segment_of_eye)
- q14_(congenital_malformations_of_posterior_segment_of_eye)
- q15_(other_congenital_malformations_of_eye)
- q16_(congenital_malformations_of_ear_causing_impairment_of_hearing)
- q17_(other_congenital_malformations_of_ear)
- q18_(other_congenital_malformations_of_face_and_neck)
- q20_(congenital_malformations_of_cardiac_chambers_and_connexions)
- q21_(congenital_malformations_of_cardiac_septa)
- q22_(congenital_malformations_of_pulmonary_and_tricuspid_valves)
- q23_(congenital_malformations_of_aortic_and_mitral_valves)
- q24_(other_congenital_malformations_of_heart)
- q25_(congenital_malformations_of_great_arteries)
- q26_(congenital_malformations_of_great_veins)
- q27_(other_congenital_malformations_of_peripheral_vascular_system)
- q28_(other_congenital_malformations_of_circulatory_system)
- q30_(congenital_malformations_of_nose)
- q31_(congenital_malformations_of_larynx)
- q32_(congenital_malformations_of_trachea_and_bronchus)
- q33_(congenital_malformations_of_lung)
- q34_(other_congenital_malformations_of_respiratory_system)
- q35_(cleft_palate)
- q36_(cleft_lip)
- q37_(cleft_palate_with_cleft_lip)
- q38_(other_congenital_malformations_of_tongue,_mouth_and_pharynx)
- q39_(congenital_malformations_of_oesophagus)
- q40_(other_congenital_malformations_of_upper_alimentary_tract)
- q41_(congenital_absence,_atresia_and_stenosis_of_small_intestine)
- q42_(congenital_absence,_atresia_and_stenosis_of_large_intestine)
- q43_(other_congenital_malformations_of_intestine)
- q44_(congenital_malformations_of_gallbladder,_bile_ducts_and_liver)
- q45_(other_congenital_malformations_of_digestive_system)
- q50_(congenital_malformations_of_ovaries,_fallopian_tubes_and_broad_ligaments)
- q51_(congenital_malformations_of_uterus_and_cervix)
- q52_(other_congenital_malformations_of_female_genitalia)
- q53_(undescended_testicle)
- q54_(hypospadias)
- q55_(other_congenital_malformations_of_male_genital_organs)
- q56_(indeterminate_sex_and_pseudohermaphroditism)
- q60_(renal_agenesis_and_other_reduction_defects_of_kidney)
- q61_(cystic_kidney_disease)
- q62_(congenital_obstructive_defects_of_renal_pelvis_and_congenital_malformations_of_ureter)
- q63_(other_congenital_malformations_of_kidney)
- q64_(other_congenital_malformations_of_urinary_system)
- q65_(congenital_deformities_of_hip)
- q66_(congenital_deformities_of_feet)
- q67_(congenital_musculoskeletal_deformities_of_head,_face,_spine_and_chest)
- q68_(other_congenital_musculoskeletal_deformities)
- q69_(polydactyly)
- q70_(syndactyly)
- q71_(reduction_defects_of_upper_limb)
- q72_(reduction_defects_of_lower_limb)
- q73_(reduction_defects_of_unspecified_limb)
- q74_(other_congenital_malformations_of_limb(s))
- q75_(other_congenital_malformations_of_skull_and_face_bones)
- q76_(congenital_malformations_of_spine_and_bony_thorax)
- q77_(osteochondrodysplasia_with_defects_of_growth_of_tubular_bones_and_spine)
- q78_(other_osteochondrodysplasias)
- q79_(congenital_malformations_of_musculoskeletal_system,_not_elsewhere_classified)
- q80_(congenital_ichthyosis)
- q81_(epidermolysis_bullosa)
- q82_(other_congenital_malformations_of_skin)
- q83_(congenital_malformations_of_breast)
- q84_(other_congenital_malformations_of_integument)
- q85_(phakomatoses,_not_elsewhere_classified)
- q86_(congenital_malformation_syndromes_due_to_known_exogenous_causes,_not_elsewhere_classified)
- q87_(other_specified_congenital_malformation_syndromes_affecting_multiple_systems)
- q89_(other_congenital_malformations,_not_elsewhere_classified)
- q90_(down's_syndrome)
- q91_(edwards'_syndrome_and_patau's_syndrome)
- q92_(other_trisomies_and_partial_trisomies_of_the_autosomes,_not_elsewhere_classified)
- q93_(monosomies_and_deletions_from_the_autosomes,_not_elsewhere_classified)
- q95_(balanced_rearrangements_and_structural_markers,_not_elsewhere_classified)
- q96_(turner's_syndrome)
- q97_(other_sex_chromosome_abnormalities,_female_phenotype,_not_elsewhere_classified)
- q98_(other_sex_chromosome_abnormalities,_male_phenotype,_not_elsewhere_classified)
- q99_(other_chromosome_abnormalities,_not_elsewhere_classified)
