model_type: motor
ckpt_dir: mimic
eval_interval: 500
eval_iters: 25
eval_only: false
init_from: scratch
seed: 42
gradient_accumulation_steps: 1
batch_size: 256
device: cuda
data:
  data_dir: mimic
  seed: 42
  block_size: ${model.block_size}
  timestep: since_start
model:
  vocab_size: 4544
  n_layer: 10
  n_head: 8
  n_embd: 256
  embd_pdrop: 0.3
  bias: true
  block_size: 1024
  ce_beta: 0.0
  motor_beta: 1.0
  motor_n_hidden: 32
  motor_pieces: config/time_interval/ukb-motor-12piece-preset.yaml
  motor_task_tokens: all
log:
  wandb_log: true
  wandb_project: ${ckpt_dir}
  run_name: motor-12piece-preset
  log_interval: 25
  always_ckpt_after_eval: true
  ckpt_interval: null
optim:
  learning_rate: 6e-4
  max_iters: 50000
  weight_decay: 2e-1
  lr_decay_iters: ${optim.max_iters}
  min_lr: 6e-5
  beta2: 0.99
  warmup_iters: 1000
