ckpt_dir: motor
eval_interval: 500
eval_iters: 25
eval_only: false
init_from: scratch
seed: 42
gradient_accumulation_steps: 1
batch_size: 512
device: cuda
model_type: motor
train_data:
  data_dir: ukb_real_data
  subject_list: ukb_real_data/participants/train_fold.bin
  seed: 42
  no_event_interval: 5
val_data:
  data_dir: ukb_real_data
  subject_list: ukb_real_data/participants/val_fold.bin
  seed: 42
  no_event_interval: 5
model:
  n_layer: 12
  n_head: 12
  n_embd: 120
  dropout: 0.1
  token_dropout: 0.0
  bias: true
  ce_beta: 0.0
  motor_beta: 1.0
  motor_n_hidden: 32
  motor_time_bins:
    - 0
    - 300
    - 600
    - 900
    - 1200
  motor_task_tokens: all
log:
  wandb_log: true
  wandb_project: ${ckpt_dir}
  run_name: baseline
  log_interval: 25
  always_ckpt_after_eval: true
  ckpt_interval: null
optim:
  learning_rate: 6e-4
  max_iters: 100000
  weight_decay: 2e-1
  lr_decay_iters: 100000
  min_lr: 6e-5
  beta2: 0.99
  warmup_iters: 1000
