task_name: ${task_args.n_samples}samples-${task_args.start_age_years}start-${task_args.end_age_years}end
task_type: ukb-forecast
task_args:
  data:
    data_dir: ukb_real_data
    subject_list: participants/val_fold.bin
    no_event_interval: 1826.25
    block_size: 256
    seed: 42
  batch_size: 150
  n_samples: 30
  start_age_years: 50
  end_age_years: 85
