data:
  data_dir: ukb_real_data
  subject_list: participants/val_fold.bin
  no_event_interval: 1826.25
  block_size: 256
  seed: 42
batch_size: 150
n_samples: 30
start_age_years: 50
end_age_years: 85
log_name: ${n_samples}samples-${start_age_years}start-${end_age_years}end
