tasks:
- task_name: debug_auc
  task_type: auc
  # task_input: debug_forward
  task_input: debug_gen
  task_args:
    diseases:
      - a41_(other_septicaemia)
    min_time_gap: 0.1
    box_plot: false
    age_groups:
      start: 40
      end: 85
      step: 5
    time_offset:
      # groups: [0, 1]
      start: 0
      end: 10
      step: 1
# - task_name: debug_incidence
#   task_type: incidence
#   task_args:
#     diseases:
#       - a41_(other_septicaemia)
#     train_data_memmap: data/ukb_simulated_data/train.bin
#     val_data_memmap: data/ukb_simulated_data/val.bin
#     sample_size: 1000
#     device: cpu
# - task_name: debug_calibration
#   task_type: calibration
#   task_input: debug_forward
#   task_args:
#     diseases:
#       - a41_(other_septicaemia)
#     min_time_gap: 0.1
# - task_name: debug_burden
#   task_type: burden
#   task_input: debug_gen
#   task_args:
#     box_plot: true
#     gen_name: debug_gen
