name: debug_eval
ckpt_path: checkpoints/Delphi-demo
tasks:
- task_name: debug_auc
  task_type: auc
  task_args:
    diseases:
      - a41_(other_septicaemia)
    data_memmap: data/ukb_simulated_data/val.bin
    sample_size: 1000
    device: cpu
    min_time_gap: 0.1
    box_plot: true
- task_name: debug_incidence
  task_type: incidence
  task_args:
    diseases:
      - a41_(other_septicaemia)
    train_data_memmap: data/ukb_simulated_data/train.bin
    val_data_memmap: data/ukb_simulated_data/val.bin
    sample_size: 1000
    device: cpu
