name: forward
device: cuda
batch_size: 128
subsample: null
use_val_data: true
data:
  data_dir: ukb_real_data
  memmap_fname: val.bin
  tokenizer_fname: tokenizer.yaml
  prs:
    lmdb_fname: prs.lmdb
    include: true
    must: true
  transforms:
    - name: no-event
      args:
        interval_in_years: 5
        mode: random
log:
  save_tokens: true
  save_logits: true
  flush_interval: 10
  wandb_log: false
