name: debug_forward
device: mps
batch_size: 128
subsample: null
data:
  data_dir: data/ukb_real_data
  memmap_fname: val.bin
  tokenizer_fname: tokenizer.yaml
  transforms:
    - name: no-event
      args:
        interval_in_years: 5
        mode: random
log:
  save_tokens: true
  save_logits: true
  flush_interval: 10
  wandb_log: false
