name: debug_forward
device: cpu
batch_size: 128
subsample: 1280
data:
  data_dir: data/ukb_simulated_data_large
  memmap_fname: train.bin
  tokenizer_fname: tokenizer.yaml
  transforms:
    - name: no-event
      args:
        interval_in_years: 5
        mode: random
log:
  save_tokens: true
  save_logits: true
  flush_interval: 10
  wandb_log: false
