name: debug_gen
device: cpu
batch_size: 128
subsample: 256
start_age_in_years: 60
data:
  data_dir: data/ukb_simulated_data_large
  memmap_fname: train.bin
  tokenizer_fname: tokenizer.yaml
  transforms:
    - name: no-event
      args:
        interval_in_years: 5
        mode: random
sampler:
  seed: 42
  no_repeat: true
  top_k: null
  temperature: 1.0
  max_age_in_years: 80
  max_new_tokens: 64
  max_total_tokens: 128
  termination_tokens:
    - death
  simulate_comorbid: true
  comorbid_cutoff: 0.08
  always_single_tokens:
    - no_event
    - death
log:
  save_tokens: true
  save_logits: true
  flush_interval: 10
  wandb_log: true
