name: gen_from_${start_age_in_years}
device: mps
batch_size: 128
subsample: null
start_age_in_years: 40
data:
  data_dir: ${oc.env:DELPHI_DATA_DIR,data}/ukb_real_data
  memmap_fname: val.bin
  tokenizer_fname: tokenizer.yaml
  transforms:
    - name: no-event
      args:
        interval_in_years: 5
        mode: random
sampler:
  seed: 42
  no_repeat: true
  top_k: null
  temperature: 1.0
  max_age_in_years: 80
  max_new_tokens: 64
  max_total_tokens: 128
  termination_tokens:
    - death
  zero_inflate: false
  simulate_comorbid: false
  comorbid_cutoff: 0.08
  always_single_tokens:
    - no_event
    - death
log:
  save_tokens: true
  save_logits: true
  flush_interval: 10
  wandb_log: true
