ckpt_dir: debug
eval_interval: 25
eval_iters: 25
eval_only: false
init_from: scratch
seed: 42
gradient_accumulation_steps: 1
batch_size: 128
device: cuda

infer_train_biomarkers: true
train_data:
  data_dir: ukb_real_data
  subject_list: ukb_real_data/participants/train_fold.bin
  seed: 42
  biomarker_dir: ukb_real_data/biomarkers
  expansion_pack_dir: ukb_real_data/expansion_packs
  expansion_packs:
    - fsf
    - summary_ops
    - ops
    - prescriptions
  transforms:
    - name: no-event
      args:
        interval_in_years: 5
        mode: random
infer_val_biomarkers: true
infer_val_expansion_packs: true
val_data:
  data_dir: ukb_real_data
  subject_list: ukb_real_data/participants/val_fold.bin
  seed: 42
  biomarker_dir: ukb_real_data/biomarkers
  expansion_pack_dir: ukb_real_data/expansion_packs
  transforms:
    - name: no-event
      args:
        interval_in_years: 5
        mode: random
model:
  block_size: 48
  # delphi-2m vocab_size: 1270
  # fsf vocab size: 9
  # summary_ops vocab size: 1565
  # ops vocab size: 253
  # prescriptions vocab size: 351
  n_layer: 12
  n_head: 12
  n_embd: 120
  dropout: 0.1
  token_dropout: 0.0
  t_min: 0.1
  bias: true
  mask_ties: true
  ignore_tokens:
    - padding
    - male
    - female
    - config/disease_list/lifestyle.yaml
    - config/disease_list/ops.yaml
    - config/disease_list/summary_ops.yaml
    - config/disease_list/fsf.yaml
    - config/disease_list/prescriptions.yaml
  biomarkers:
    prs:
      projector: linear
      input_size: 36
    blood_all:
      projector: linear
      input_size: 57
  #   wbc:
  #     projector: linear
  #     input_size: 31
  #   lipid:
  #     projector: linear
  #     input_size: 4
  #   lft:
  #     projector: linear
  #     input_size: 7
  #   renal:
  #     projector: linear
  #     input_size: 6
  #   hba1c:
  #     projector: linear
  #     input_size: 1
  #   crp:
  #     projector: linear
  #     input_size: 1
  #   urate:
  #     projector: linear
  #     input_size: 1
  #   cysc:
  #     projector: linear
  #     input_size: 1
  #   apo:
  #     projector: linear
  #     input_size: 2
  #   vitd:
  #     projector: linear
  #     input_size: 1
  #   dht:
  #     projector: linear
  #     input_size: 1
  #   shbg:
  #     projector: linear
  #     input_size: 1
  #   igf1:
  #     projector: linear
  #     input_size: 1
    nak:
      projector: linear
      input_size: 2
    creat:
      projector: linear
      input_size: 1
    albu:
      projector: linear
      input_size: 1
    diet:
      projector: linear
      input_size: 16
    met:
      projector: linear
      input_size: 3
    telomere:
      projector: linear
      input_size: 1
  modality_emb: true
  loss:
    ce_beta: 1.0
    dt_beta: 1.0
    zero_inflate: false
log:
  wandb_log: true
  wandb_project: ${ckpt_dir}
  run_name: debug
  log_interval: 25
  always_ckpt_after_eval: true
  ckpt_interval: null
optim:
  learning_rate: 6e-4 # with baby networks can afford to go a bit higher
  max_iters: 100000
  weight_decay: 2e-1
  lr_decay_iters: 100000 # make equal to max_iters usually
  min_lr: 6e-5 # learning_rate / 10 usually
  beta2: 0.99 # make a bit bigger because number of tokens per iter is small
  warmup_iters: 1000 # not super necessary potentially
