- a41_(other_septicaemia)
- b01_(varicella_[chickenpox])
- c25_malignant_neoplasm_of_pancreas
- c50_malignant_neoplasm_of_breast
- g30_(alzheimer's_disease)
- e10_(insulin-dependent_diabetes_mellitus)
- f32_(depressive_episode)
- i21_(acute_myocardial_infarction)
- j45_(asthma)
- death
