- family_hx_hip_fracture
- family_hx_prostate_cancer
- family_hx_severe_depression
- family_hx_parkinsons_disease
- family_hx_alzheimers_disease_dementia
- family_hx_diabetes
- family_hx_high_blood_pressure
- family_hx_chronic_bronchitis_emphysema
- family_hx_breast_cancer
- family_hx_bowel_cancer
- family_hx_lung_cancer
- family_hx_stroke
- family_hx_heart_disease
