- cxx_unknown_cancer
- c00_malignant_neoplasm_of_lip
- c01_malignant_neoplasm_of_base_of_tongue
- c02_malignant_neoplasm_of_other_and_unspecified_parts_of_tongue
- c03_malignant_neoplasm_of_gum
- c04_malignant_neoplasm_of_floor_of_mouth
- c05_malignant_neoplasm_of_palate
- c06_malignant_neoplasm_of_other_and_unspecified_parts_of_mouth
- c07_malignant_neoplasm_of_parotid_gland
- c08_malignant_neoplasm_of_other_and_unspecified_major_salivary_glands
- c09_malignant_neoplasm_of_tonsil
- c10_malignant_neoplasm_of_oropharynx
- c11_malignant_neoplasm_of_nasopharynx
- c12_malignant_neoplasm_of_pyriform_sinus
- c13_malignant_neoplasm_of_hypopharynx
- c14_malignant_neoplasm_of_other_and_ill-defined_sites_in_the_lip,_oral_cavity_and_pharynx
- c15_malignant_neoplasm_of_oesophagus
- c16_malignant_neoplasm_of_stomach
- c17_malignant_neoplasm_of_small_intestine
- c18_malignant_neoplasm_of_colon
- c19_malignant_neoplasm_of_rectosigmoid_junction
- c20_malignant_neoplasm_of_rectum
- c21_malignant_neoplasm_of_anus_and_anal_canal
- c22_malignant_neoplasm_of_liver_and_intrahepatic_bile_ducts
- c23_malignant_neoplasm_of_gallbladder
- c24_malignant_neoplasm_of_other_and_unspecified_parts_of_biliary_tract
- c25_malignant_neoplasm_of_pancreas
- c26_malignant_neoplasm_of_other_and_ill-defined_digestive_organs
- c30_malignant_neoplasm_of_nasal_cavity_and_middle_ear
- c31_malignant_neoplasm_of_accessory_sinuses
- c32_malignant_neoplasm_of_larynx
- c33_malignant_neoplasm_of_trachea
- c34_malignant_neoplasm_of_bronchus_and_lung
- c37_malignant_neoplasm_of_thymus
- c38_malignant_neoplasm_of_heart,_mediastinum_and_pleura
- c39_malignant_neoplasm_of_other_and_ill-defined_sites_in_the_respiratory_system_and_intrathoracic_organs
- c40_malignant_neoplasm_of_bone_and_articular_cartilage_of_limbs
- c41_malignant_neoplasm_of_bone_and_articular_cartilage_of_other_and_unspecified_sites
- c42_hematopoietic_and_reticuloendothelial_systems_(icd-o-3_specific)
- c43_malignant_melanoma_of_skin
- c44_other_malignant_neoplasms_of_skin
- c45_mesothelioma
- c46_kaposi's_sarcoma
- c47_malignant_neoplasm_of_peripheral_nerves_and_autonomic_nervous_system
- c48_malignant_neoplasm_of_retroperitoneum_and_peritoneum
- c49_malignant_neoplasm_of_other_connective_and_soft_tissue
- c50_malignant_neoplasm_of_breast
- c51_malignant_neoplasm_of_vulva
- c52_malignant_neoplasm_of_vagina
- c53_malignant_neoplasm_of_cervix_uteri
- c54_malignant_neoplasm_of_corpus_uteri
- c55_malignant_neoplasm_of_uterus,_part_unspecified
- c56_malignant_neoplasm_of_ovary
- c57_malignant_neoplasm_of_other_and_unspecified_female_genital_organs
- c58_malignant_neoplasm_of_placenta
- c60_malignant_neoplasm_of_penis
- c61_malignant_neoplasm_of_prostate
- c62_malignant_neoplasm_of_testis
- c63_malignant_neoplasm_of_other_and_unspecified_male_genital_organs
- c64_malignant_neoplasm_of_kidney,_except_renal_pelvis
- c65_malignant_neoplasm_of_renal_pelvis
- c66_malignant_neoplasm_of_ureter
- c67_malignant_neoplasm_of_bladder
- c68_malignant_neoplasm_of_other_and_unspecified_urinary_organs
- c69_malignant_neoplasm_of_eye_and_adnexa
- c70_malignant_neoplasm_of_meninges
- c71_malignant_neoplasm_of_brain
- c72_malignant_neoplasm_of_spinal_cord,_cranial_nerves_and_other_parts_of_central_nervous_system
- c73_malignant_neoplasm_of_thyroid_gland
- c74_malignant_neoplasm_of_adrenal_gland
- c75_malignant_neoplasm_of_other_endocrine_glands_and_related_structures
- c76_malignant_neoplasm_of_other_and_ill-defined_sites
- c77_secondary_and_unspecified_malignant_neoplasm_of_lymph_nodes
- c78_secondary_malignant_neoplasm_of_respiratory_and_digestive_organs
- c79_secondary_malignant_neoplasm_of_other_sites
- c80_malignant_neoplasm_without_specification_of_site
- c81_hodgkin's_disease
- c82_follicular_[nodular]_non-hodgkin's_lymphoma
- c83_diffuse_non-hodgkin's_lymphoma
- c84_peripheral_and_cutaneous_t-cell_lymphomas
- c85_other_and_unspecified_types_of_non-hodgkin's_lymphoma
- c86_other_specified_types_of_t/nk-cell_lymphoma
- c88_malignant_immunoproliferative_diseases
- c90_multiple_myeloma_and_malignant_plasma_cell_neoplasms
- c91_lymphoid_leukaemia
- c92_myeloid_leukaemia
- c93_monocytic_leukaemia
- c94_other_leukaemias_of_specified_cell_type
- c95_leukaemia_of_unspecified_cell_type
- c96_other_and_unspecified_malignant_neoplasms_of_lymphoid,_haematopoietic_and_related_tissue
- c97_malignant_neoplasms_of_independent_(primary)_multiple_sites
- d00_carcinoma_in_situ_of_oral_cavity,_oesophagus_and_stomach
- d01_carcinoma_in_situ_of_other_and_unspecified_digestive_organs
- d02_carcinoma_in_situ_of_middle_ear_and_respiratory_system
- d03_melanoma_in_situ
- d04_carcinoma_in_situ_of_skin
- d05_carcinoma_in_situ_of_breast
- d06_carcinoma_in_situ_of_cervix_uteri
- d07_carcinoma_in_situ_of_other_and_unspecified_genital_organs
- d09_carcinoma_in_situ_of_other_and_unspecified_sites
- d10_benign_neoplasm_of_mouth_and_pharynx
- d11_benign_neoplasm_of_major_salivary_glands
- d12_benign_neoplasm_of_colon,_rectum,_anus_and_anal_canal
- d13_benign_neoplasm_of_other_and_ill-defined_parts_of_digestive_system
- d15_benign_neoplasm_of_other_and_unspecified_intrathoracic_organs
- d16_benign_neoplasm_of_bone_and_articular_cartilage
- d18_haemangioma_and_lymphangioma,_any_site
- d27_benign_neoplasm_of_ovary
- d30_benign_neoplasm_of_urinary_organs
- d32_benign_neoplasm_of_meninges
- d33_benign_neoplasm_of_brain_and_other_parts_of_central_nervous_system
- d34_benign_neoplasm_of_thyroid_gland
- d35_benign_neoplasm_of_other_and_unspecified_endocrine_glands
- d36_benign_neoplasm_of_other_and_unspecified_sites
- d37_neoplasm_of_uncertain_or_unknown_behaviour_of_oral_cavity_and_digestive_organs
- d38_neoplasm_of_uncertain_or_unknown_behaviour_of_middle_ear_and_respiratory_and_intrathoracic_organs
- d39_neoplasm_of_uncertain_or_unknown_behaviour_of_female_genital_organs
- d40_neoplasm_of_uncertain_or_unknown_behaviour_of_male_genital_organs
- d41_neoplasm_of_uncertain_or_unknown_behaviour_of_urinary_organs
- d42_neoplasm_of_uncertain_or_unknown_behaviour_of_meninges
- d43_neoplasm_of_uncertain_or_unknown_behaviour_of_brain_and_central_nervous_system
- d44_neoplasm_of_uncertain_or_unknown_behaviour_of_endocrine_glands
- d45_polycythaemia_vera
- d46_myelodysplastic_syndromes
- d47_other_neoplasms_of_uncertain_or_unknown_behaviour_of_lymphoid,_haematopoietic_and_related_tissue
- d48_neoplasm_of_uncertain_or_unknown_behaviour_of_other_and_unspecified_sites
