- d50_(iron_deficiency_anaemia)
- d51_(vitamin_b12_deficiency_anaemia)
- d52_(folate_deficiency_anaemia)
- d53_(other_nutritional_anaemias)
- d55_(anaemia_due_to_enzyme_disorders)
- d56_(thalassaemia)
- d57_(sickle-cell_disorders)
- d58_(other_hereditary_haemolytic_anaemias)
- d59_(acquired_haemolytic_anaemia)
- d60_(acquired_pure_red_cell_aplasia_[erythroblastopenia])
- d61_(other_aplastic_anaemias)
- d62_(acute_posthaemorrhagic_anaemia)
- d63_(anaemia_in_chronic_diseases_classified_elsewhere)
- d64_(other_anaemias)
- d65_(disseminated_intravascular_coagulation_[defibrination_syndrome])
- d66_(hereditary_factor_viii_deficiency)
- d67_(hereditary_factor_ix_deficiency)
- d68_(other_coagulation_defects)
- d69_(purpura_and_other_haemorrhagic_conditions)
- d70_(agranulocytosis)
- d71_(functional_disorders_of_polymorphonuclear_neutrophils)
- d72_(other_disorders_of_white_blood_cells)
- d73_(diseases_of_spleen)
- d74_(methaemoglobinaemia)
- d75_(other_diseases_of_blood_and_blood-forming_organs)
- d76_(certain_diseases_involving_lymphoreticular_tissue_and_reticulohistiocytic_system)
- d77_(other_disorders_of_blood_and_blood-forming_organs_in_diseases_classified_elsewhere)
- d80_(immunodeficiency_with_predominantly_antibody_defects)
- d81_(combined_immunodeficiencies)
- d82_(immunodeficiency_associated_with_other_major_defects)
- d83_(common_variable_immunodeficiency)
- d84_(other_immunodeficiencies)
- d86_(sarcoidosis)
- d89_(other_disorders_involving_the_immune_mechanism,_not_elsewhere_classified)
