- h60_(otitis_externa)
- h61_(other_disorders_of_external_ear)
- h62_(disorders_of_external_ear_in_diseases_classified_elsewhere)
- h65_(nonsuppurative_otitis_media)
- h66_(suppurative_and_unspecified_otitis_media)
- h67_(otitis_media_in_diseases_classified_elsewhere)
- h68_(eustachian_salpingitis_and_obstruction)
- h69_(other_disorders_of_eustachian_tube)
- h70_(mastoiditis_and_related_conditions)
- h71_(cholesteatoma_of_middle_ear)
- h72_(perforation_of_tympanic_membrane)
- h73_(other_disorders_of_tympanic_membrane)
- h74_(other_disorders_of_middle_ear_and_mastoid)
- h75_(other_disorders_of_middle_ear_and_mastoid_in_diseases_classified_elsewhere)
- h80_(otosclerosis)
- h81_(disorders_of_vestibular_function)
- h82_(vertiginous_syndromes_in_diseases_classified_elsewhere)
- h83_(other_diseases_of_inner_ear)
- h90_(conductive_and_sensorineural_hearing_loss)
- h91_(other_hearing_loss)
- h92_(otalgia_and_effusion_of_ear)
- h93_(other_disorders_of_ear,_not_elsewhere_classified)
- h94_(other_disorders_of_ear_in_diseases_classified_elsewhere)
- h95_(postprocedural_disorders_of_ear_and_mastoid_process,_not_elsewhere_classified)
