- j00_(acute_nasopharyngitis_[common_cold])
- j01_(acute_sinusitis)
- j02_(acute_pharyngitis)
- j03_(acute_tonsillitis)
- j04_(acute_laryngitis_and_tracheitis)
- j05_(acute_obstructive_laryngitis_[croup]_and_epiglottitis)
- j06_(acute_upper_respiratory_infections_of_multiple_and_unspecified_sites)
- j09_(influenza_due_to_certain_identified_influenza_virus)
- j10_(influenza_due_to_identified_influenza_virus)
- j11_(influenza,_virus_not_identified)
- j12_(viral_pneumonia,_not_elsewhere_classified)
- j13_(pneumonia_due_to_streptococcus_pneumoniae)
- j14_(pneumonia_due_to_haemophilus_influenzae)
- j15_(bacterial_pneumonia,_not_elsewhere_classified)
- j16_(pneumonia_due_to_other_infectious_organisms,_not_elsewhere_classified)
- j17_(pneumonia_in_diseases_classified_elsewhere)
- j18_(pneumonia,_organism_unspecified)
- j20_(acute_bronchitis)
- j21_(acute_bronchiolitis)
- j22_(unspecified_acute_lower_respiratory_infection)
- j30_(vasomotor_and_allergic_rhinitis)
- j31_(chronic_rhinitis,_nasopharyngitis_and_pharyngitis)
- j32_(chronic_sinusitis)
- j33_(nasal_polyp)
- j34_(other_disorders_of_nose_and_nasal_sinuses)
- j35_(chronic_diseases_of_tonsils_and_adenoids)
- j36_(peritonsillar_abscess)
- j37_(chronic_laryngitis_and_laryngotracheitis)
- j38_(diseases_of_vocal_cords_and_larynx,_not_elsewhere_classified)
- j39_(other_diseases_of_upper_respiratory_tract)
- j40_(bronchitis,_not_specified_as_acute_or_chronic)
- j41_(simple_and_mucopurulent_chronic_bronchitis)
- j42_(unspecified_chronic_bronchitis)
- j43_(emphysema)
- j44_(other_chronic_obstructive_pulmonary_disease)
- j45_(asthma)
- j46_(status_asthmaticus)
- j47_(bronchiectasis)
- j60_(coalworker's_pneumoconiosis)
- j61_(pneumoconiosis_due_to_asbestos_and_other_mineral_fibres)
- j62_(pneumoconiosis_due_to_dust_containing_silica)
- j63_(pneumoconiosis_due_to_other_inorganic_dusts)
- j64_(unspecified_pneumoconiosis)
- j66_(airway_disease_due_to_specific_organic_dust)
- j67_(hypersensitivity_pneumonitis_due_to_organic_dust)
- j68_(respiratory_conditions_due_to_inhalation_of_chemicals,_gases,_fumes_and_vapours)
- j69_(pneumonitis_due_to_solids_and_liquids)
- j70_(respiratory_conditions_due_to_other_external_agents)
- j80_(adult_respiratory_distress_syndrome)
- j81_(pulmonary_oedema)
- j82_(pulmonary_eosinophilia,_not_elsewhere_classified)
- j84_(other_interstitial_pulmonary_diseases)
- j85_(abscess_of_lung_and_mediastinum)
- j86_(pyothorax)
- j90_(pleural_effusion,_not_elsewhere_classified)
- j91_(pleural_effusion_in_conditions_classified_elsewhere)
- j92_(pleural_plaque)
- j93_(pneumothorax)
- j94_(other_pleural_conditions)
- j95_(postprocedural_respiratory_disorders,_not_elsewhere_classified)
- j96_(respiratory_failure,_not_elsewhere_classified)
- j98_(other_respiratory_disorders)
- j99_(respiratory_disorders_in_diseases_classified_elsewhere)
