- k00_(disorders_of_tooth_development_and_eruption)
- k01_(embedded_and_impacted_teeth)
- k02_(dental_caries)
- k03_(other_diseases_of_hard_tissues_of_teeth)
- k04_(diseases_of_pulp_and_periapical_tissues)
- k05_(gingivitis_and_periodontal_diseases)
- k06_(other_disorders_of_gingiva_and_edentulous_alveolar_ridge)
- k07_(dentofacial_anomalies_[including_malocclusion])
- k08_(other_disorders_of_teeth_and_supporting_structures)
- k09_(cysts_of_oral_region,_not_elsewhere_classified)
- k10_(other_diseases_of_jaws)
- k11_(diseases_of_salivary_glands)
- k12_(stomatitis_and_related_lesions)
- k13_(other_diseases_of_lip_and_oral_mucosa)
- k14_(diseases_of_tongue)
- k20_(oesophagitis)
- k21_(gastro-oesophageal_reflux_disease)
- k22_(other_diseases_of_oesophagus)
- k23_(disorders_of_oesophagus_in_diseases_classified_elsewhere)
- k25_(gastric_ulcer)
- k26_(duodenal_ulcer)
- k27_(peptic_ulcer,_site_unspecified)
- k28_(gastrojejunal_ulcer)
- k29_(gastritis_and_duodenitis)
- k30_(dyspepsia)
- k31_(other_diseases_of_stomach_and_duodenum)
- k35_(acute_appendicitis)
- k36_(other_appendicitis)
- k37_(unspecified_appendicitis)
- k38_(other_diseases_of_appendix)
- k40_(inguinal_hernia)
- k41_(femoral_hernia)
- k42_(umbilical_hernia)
- k43_(ventral_hernia)
- k44_(diaphragmatic_hernia)
- k45_(other_abdominal_hernia)
- k46_(unspecified_abdominal_hernia)
- k50_(crohn's_disease_[regional_enteritis])
- k51_(ulcerative_colitis)
- k52_(other_non-infective_gastro-enteritis_and_colitis)
- k55_(vascular_disorders_of_intestine)
- k56_(paralytic_ileus_and_intestinal_obstruction_without_hernia)
- k57_(diverticular_disease_of_intestine)
- k58_(irritable_bowel_syndrome)
- k59_(other_functional_intestinal_disorders)
- k60_(fissure_and_fistula_of_anal_and_rectal_regions)
- k61_(abscess_of_anal_and_rectal_regions)
- k62_(other_diseases_of_anus_and_rectum)
- k63_(other_diseases_of_intestine)
- k64_(haemorrhoids_and_perianal_venous_thrombosis)
- k65_(peritonitis)
- k66_(other_disorders_of_peritoneum)
- k67_(disorders_of_peritoneum_in_infectious_diseases_classified_elsewhere)
- k70_(alcoholic_liver_disease)
- k71_(toxic_liver_disease)
- k72_(hepatic_failure,_not_elsewhere_classified)
- k73_(chronic_hepatitis,_not_elsewhere_classified)
- k74_(fibrosis_and_cirrhosis_of_liver)
- k75_(other_inflammatory_liver_diseases)
- k76_(other_diseases_of_liver)
- k77_(liver_disorders_in_diseases_classified_elsewhere)
- k80_(cholelithiasis)
- k81_(cholecystitis)
- k82_(other_diseases_of_gallbladder)
- k83_(other_diseases_of_biliary_tract)
- k85_(acute_pancreatitis)
- k86_(other_diseases_of_pancreas)
- k87_(disorders_of_gallbladder,_biliary_tract_and_pancreas_in_diseases_classified_elsewhere)
- k90_(intestinal_malabsorption)
- k91_(postprocedural_disorders_of_digestive_system,_not_elsewhere_classified)
- k92_(other_diseases_of_digestive_system)
- k93_(disorders_of_other_digestive_organs_in_diseases_classified_elsewhere)
