- m00_(pyogenic_arthritis)
- m01_(direct_infections_of_joint_in_infectious_and_parasitic_diseases_classified_elsewhere)
- m02_(reactive_arthropathies)
- m03_(postinfective_and_reactive_arthropathies_in_diseases_classified_elsewhere)
- m05_(seropositive_rheumatoid_arthritis)
- m06_(other_rheumatoid_arthritis)
- m07_(psoriatic_and_enteropathic_arthropathies)
- m08_(juvenile_arthritis)
- m09_(juvenile_arthritis_in_diseases_classified_elsewhere)
- m10_(gout)
- m11_(other_crystal_arthropathies)
- m12_(other_specific_arthropathies)
- m13_(other_arthritis)
- m14_(arthropathies_in_other_diseases_classified_elsewhere)
- m15_(polyarthrosis)
- m16_(coxarthrosis_[arthrosis_of_hip])
- m17_(gonarthrosis_[arthrosis_of_knee])
- m18_(arthrosis_of_first_carpometacarpal_joint)
- m19_(other_arthrosis)
- m20_(acquired_deformities_of_fingers_and_toes)
- m21_(other_acquired_deformities_of_limbs)
- m22_(disorders_of_patella)
- m23_(internal_derangement_of_knee)
- m24_(other_specific_joint_derangements)
- m25_(other_joint_disorders,_not_elsewhere_classified)
- m30_(polyarteritis_nodosa_and_related_conditions)
- m31_(other_necrotising_vasculopathies)
- m32_(systemic_lupus_erythematosus)
- m33_(dermatopolymyositis)
- m34_(systemic_sclerosis)
- m35_(other_systemic_involvement_of_connective_tissue)
- m36_(systemic_disorders_of_connective_tissue_in_diseases_classified_elsewhere)
- m40_(kyphosis_and_lordosis)
- m41_(scoliosis)
- m42_(spinal_osteochondrosis)
- m43_(other_deforming_dorsopathies)
- m45_(ankylosing_spondylitis)
- m46_(other_inflammatory_spondylopathies)
- m47_(spondylosis)
- m48_(other_spondylopathies)
- m49_(spondylopathies_in_diseases_classified_elsewhere)
- m50_(cervical_disk_disorders)
- m51_(other_intervertebral_disk_disorders)
- m53_(other_dorsopathies,_not_elsewhere_classified)
- m54_(dorsalgia)
- m60_(myositis)
- m61_(calcification_and_ossification_of_muscle)
- m62_(other_disorders_of_muscle)
- m63_(disorders_of_muscle_in_diseases_classified_elsewhere)
- m65_(synovitis_and_tenosynovitis)
- m66_(spontaneous_rupture_of_synovium_and_tendon)
- m67_(other_disorders_of_synovium_and_tendon)
- m68_(disorders_of_synovium_and_tendon_in_diseases_classified_elsewhere)
- m70_(soft_tissue_disorders_related_to_use,_overuse_and_pressure)
- m71_(other_bursopathies)
- m72_(fibroblastic_disorders)
- m73_(soft_tissue_disorders_in_diseases_classified_elsewhere)
- m75_(shoulder_lesions)
- m76_(enthesopathies_of_lower_limb,_excluding_foot)
- m77_(other_enthesopathies)
- m79_(other_soft_tissue_disorders,_not_elsewhere_classified)
- m80_(osteoporosis_with_pathological_fracture)
- m81_(osteoporosis_without_pathological_fracture)
- m82_(osteoporosis_in_diseases_classified_elsewhere)
- m83_(adult_osteomalacia)
- m84_(disorders_of_continuity_of_bone)
- m85_(other_disorders_of_bone_density_and_structure)
- m86_(osteomyelitis)
- m87_(osteonecrosis)
- m88_(paget's_disease_of_bone_[osteitis_deformans])
- m89_(other_disorders_of_bone)
- m90_(osteopathies_in_diseases_classified_elsewhere)
- m91_(juvenile_osteochondrosis_of_hip_and_pelvis)
- m92_(other_juvenile_osteochondrosis)
- m93_(other_osteochondropathies)
- m94_(other_disorders_of_cartilage)
- m95_(other_acquired_deformities_of_musculoskeletal_system_and_connective_tissue)
- m96_(postprocedural_musculoskeletal_disorders,_not_elsewhere_classified)
- m99_(biomechanical_lesions,_not_elsewhere_classified)
