- o00_(ectopic_pregnancy)
- o01_(hydatidiform_mole)
- o02_(other_abnormal_products_of_conception)
- o03_(spontaneous_abortion)
- o04_(medical_abortion)
- o05_(other_abortion)
- o06_(unspecified_abortion)
- o07_(failed_attempted_abortion)
- o08_(complications_following_abortion_and_ectopic_and_molar_pregnancy)
- o10_(pre-existing_hypertension_complicating_pregnancy,_childbirth_and_the_puerperium)
- o11_(pre-existing_hypertensive_disorder_with_superimposed_proteinuria)
- o12_(gestational_[pregnancy-induced]_oedema_and_proteinuria_without_hypertension)
- o13_(gestational_[pregnancy-induced]_hypertension_without_significant_proteinuria)
- o14_(gestational_[pregnancy-induced]_hypertension_with_significant_proteinuria)
- o15_(eclampsia)
- o16_(unspecified_maternal_hypertension)
- o20_(haemorrhage_in_early_pregnancy)
- o21_(excessive_vomiting_in_pregnancy)
- o22_(venous_complications_in_pregnancy)
- o23_(infections_of_genito-urinary_tract_in_pregnancy)
- o24_(diabetes_mellitus_in_pregnancy)
- o25_(malnutrition_in_pregnancy)
- o26_(maternal_care_for_other_conditions_predominantly_related_to_pregnancy)
- o28_(abnormal_findings_on_antenatal_screening_of_mother)
- o29_(complications_of_anaesthesia_during_pregnancy)
- o30_(multiple_gestation)
- o31_(complications_specific_to_multiple_gestation)
- o32_(maternal_care_for_known_or_suspected_malpresentation_of_foetus)
- o33_(maternal_care_for_known_or_suspected_disproportion)
- o34_(maternal_care_for_known_or_suspected_abnormality_of_pelvic_organs)
- o35_(maternal_care_for_known_or_suspected_foetal_abnormality_and_damage)
- o36_(maternal_care_for_other_known_or_suspected_foetal_problems)
- o40_(polyhydramnios)
- o41_(other_disorders_of_amniotic_fluid_and_membranes)
- o42_(premature_rupture_of_membranes)
- o43_(placental_disorders)
- o44_(placenta_praevia)
- o45_(premature_separation_of_placenta_[abruptio_placentae])
- o46_(antepartum_haemorrhage,_not_elsewhere_classified)
- o47_(false_labour)
- o48_(prolonged_pregnancy)
- o60_(preterm_delivery)
- o61_(failed_induction_of_labour)
- o62_(abnormalities_of_forces_of_labour)
- o63_(long_labour)
- o64_(obstructed_labour_due_to_malposition_and_malpresentation_of_foetus)
- o65_(obstructed_labour_due_to_maternal_pelvic_abnormality)
- o66_(other_obstructed_labour)
- o67_(labour_and_delivery_complicated_by_intrapartum_haemorrhage,_not_elsewhere_classified)
- o68_(labour_and_delivery_complicated_by_foetal_stress_[distress])
- o69_(labour_and_delivery_complicated_by_umbilical_cord_complications)
- o70_(perineal_laceration_during_delivery)
- o71_(other_obstetric_trauma)
- o72_(postpartum_haemorrhage)
- o73_(retained_placenta_and_membranes,_without_haemorrhage)
- o74_(complications_of_anaesthesia_during_labour_and_delivery)
- o75_(other_complications_of_labour_and_delivery,_not_elsewhere_classified)
- o80_(single_spontaneous_delivery)
- o81_(single_delivery_by_forceps_and_vacuum_extractor)
- o82_(single_delivery_by_caesarean_section)
- o83_(other_assisted_single_delivery)
- o84_(multiple_delivery)
- o85_(puerperal_sepsis)
- o86_(other_puerperal_infections)
- o87_(venous_complications_in_the_puerperium)
- o88_(obstetric_embolism)
- o89_(complications_of_anaesthesia_during_the_puerperium)
- o90_(complications_of_the_puerperium,_not_elsewhere_classified)
- o91_(infections_of_breast_associated_with_childbirth)
- o92_(other_disorders_of_breast_and_lactation_associated_with_childbirth)
- o94_(sequelae_of_complication_of_pregnancy,_childbirth_and_the_puerperium)
- o96_(death_from_any_obstetric_cause_occurring_more_than_42_days_but_less_than_one_year_after_delivery)
- o98_(maternal_infectious_and_parasitic_diseases_classifiable_elsewhere_but_complicating_pregnancy,_childbirth_and_the_puerperium)
- o99_(other_maternal_diseases_classifiable_elsewhere_but_complicating_pregnancy,_childbirth_and_the_puerperium)
- o01_hydatidiform_mole38
