- p00_(foetus_and_newborn_affected_by_maternal_conditions_that_may_be_unrelated_to_present_pregnancy)
- p02_(foetus_and_newborn_affected_by_complications_of_placenta,_cord_and_membranes)
- p03_(foetus_and_newborn_affected_by_other_complications_of_labour_and_delivery)
- p04_(foetus_and_newborn_affected_by_noxious_influences_transmitted_via_placenta_or_breast_milk)
- p05_(slow_foetal_growth_and_foetal_malnutrition)
- p07_(disorders_related_to_short_gestation_and_low_birth_weight,_not_elsewhere_classified)
- p08_(disorders_related_to_long_gestation_and_high_birth_weight)
- p10_(intracranial_laceration_and_haemorrhage_due_to_birth_injury)
- p11_(other_birth_injuries_to_central_nervous_system)
- p12_(birth_injury_to_scalp)
- p13_(birth_injury_to_skeleton)
- p14_(birth_injury_to_peripheral_nervous_system)
- p15_(other_birth_injuries)
- p20_(intra-uterine_hypoxia)
- p21_(birth_asphyxia)
- p22_(respiratory_distress_of_newborn)
- p23_(congenital_pneumonia)
- p24_(neonatal_aspiration_syndromes)
- p25_(interstitial_emphysema_and_related_conditions_originating_in_the_perinatal_period)
- p26_(pulmonary_haemorrhage_originating_in_the_perinatal_period)
- p27_(chronic_respiratory_disease_originating_in_the_perinatal_period)
- p28_(other_respiratory_conditions_originating_in_the_perinatal_period)
- p29_(cardiovascular_disorders_originating_in_the_perinatal_period)
- p35_(congenital_viral_diseases)
- p36_(bacterial_sepsis_of_newborn)
- p37_(other_congenital_infectious_and_parasitic_diseases)
- p38_(omphalitis_of_newborn_with_or_without_mild_haemorrhage)
- p39_(other_infections_specific_to_the_perinatal_period)
- p50_(foetal_blood_loss)
- p51_(umbilical_haemorrhage_of_newborn)
- p52_(intracranial_nontraumatic_haemorrhage_of_foetus_and_newborn)
- p53_(haemorrhagic_disease_of_foetus_and_newborn)
- p54_(other_neonatal_haemorrhages)
- p55_(haemolytic_disease_of_foetus_and_newborn)
- p58_(neonatal_jaundice_due_to_other_excessive_haemolysis)
- p59_(neonatal_jaundice_from_other_and_unspecified_causes)
- p61_(other_perinatal_haematological_disorders)
- p70_(transitory_disorders_of_carbohydrate_metabolism_specific_to_foetus_and_newborn)
- p71_(transitory_neonatal_disorders_of_calcium_and_magnesium_metabolism)
- p78_(other_perinatal_digestive_system_disorders)
- p83_(other_conditions_of_integument_specific_to_foetus_and_newborn)
- p91_(other_disturbances_of_cerebral_status_of_newborn)
- p92_(feeding_problems_of_newborn)
- p94_(disorders_of_muscle_tone_of_newborn)
- p95_(foetal_death_of_unspecified_cause)
- p96_(other_conditions_originating_in_the_perinatal_period)
