data:
  data_dir: ukb_real_data
  subject_list: participants/val_fold.bin
  no_event_interval: 1826.25
  block_size: 256
  seed: 42
disease_lst: config/disease_list/doi.yaml
min_time_gap: 0.1
age_groups:
  bin_start: 40
  bin_end: 80
  bin_width: 5
log_name: auc-min_tim_gap_${min_time_gap}
