task_name: auc
task_type: auc
task_input: forward
task_args:
  disease_lst: config/disease_list/doi.yaml
  min_time_gap: 0.1
  box_plot: false
  age_groups:
    start: 40
    end: 85
    step: 5
  time_offset:
    start: 0
    end: 10
    step: 1
