task_name: compare_with_no_prs
task_type: compare_auc
task_input: forward/auc
task_args:
  disease_lst: config/disease_list/all.yaml
  ctrl_auc_dir: checkpoints/prs/delphi-ckpt/delphi-no-prs/forward/auc
