task_name: compare_with_no_prs
task_type: compare_auc
task_input: forward/auc
task_args:
  disease_lst: config/disease_list/all_at_least_25.yaml
  gender: either
  male_only_disease_lst: config/disease_list/male_only.yaml
  female_only_disease_lst: config/disease_list/female_only.yaml
  ctrl_ckpt: prs/delphi-ckpt/delphi-no-prs
  ctrl_task_input: ${task_input}
  plot_name: all_at_least_25
