task_name: ${task_type}-bl_${task_args.baseline_estimate}-step_${task_args.age_groups.step}
task_type: cumul_risk_auc
task_input: forward
task_args:
  disease_lst: config/disease_list/doi.yaml
  age_groups:
    start: 40
    end: 85
    step: 1
  baseline_estimate: model
